import assert from "node:assert/strict";
import {after,before,beforeEach,describe,test} from "node:test";
import type {Pool} from "pg";
import {assertSafeTestDatabase,createDatabasePool,loadDatabaseConfig,resetTestDatabase,PostgresEditorialNewsRepository,PostgresVerificationRepository,PostgresEditorialDraftRepository,PostgresHumanEditorialReviewRepository} from "../../database/src/index.ts";
import {createApprovedWorkflowFixture,EditorialWorkflowService,VerificationWorkflowService,EditorialDraftWorkflowService,HumanEditorialReviewService,HumanEditorialReviewError} from "../src/index.ts";
const config=loadDatabaseConfig();assertSafeTestDatabase(config.database);let pool:Pool;
before(async()=>{pool=createDatabasePool(config);await resetTestDatabase(pool,config)});beforeEach(async()=>{await pool.query(`TRUNCATE editorial_revision_requests,editorial_review_decisions,editorial_draft_validations,editorial_draft_citations,editorial_drafts,editorial_brief_facts,editorial_brief_claims,editorial_briefs,verification_claim_results,verification_results,verification_evidence,verification_claims,verification_runs,approval_actions,processed_commands,audit_events,editorial_relevance_results,approval_requests,draft_versions,editorial_news CASCADE`)});after(async()=>pool.end());
describe("human editorial review with PostgreSQL",()=>{
 test("lists and recovers a complete package",async()=>{const x=await seed("list");const repo=new PostgresHumanEditorialReviewRepository(pool),p=await repo.get(x.draftId);assert.equal((await repo.listPending()).length,1);assert.equal(p?.allowedFacts.length,1);assert.equal(p?.citations.length,1);assert.equal(p?.news?.state,"PENDING_APPROVAL")});
 test("approves atomically and replays",async()=>{const x=await seed("approve"),s=service();const first=await s.approve(cmd(x,"APPROVE","a"));assert.equal(first.state,"APPROVED");const events=await count("audit_events");assert.equal((await s.approve(cmd(x,"APPROVE","a"))).replayed,true);assert.equal(await count("editorial_review_decisions"),1);assert.equal(await count("audit_events"),events)});
 test("rejects with a persisted reason",async()=>{const x=await seed("reject");assert.equal((await service().reject({...cmd(x,"REJECT","r"),reason:"Não publicar"})).state,"REJECTED");assert.equal(await count("editorial_review_decisions"),1)});
 test("requests revision without creating a version",async()=>{const x=await seed("request");assert.equal((await service().requestRevision({...cmd(x,"REQUEST_REVISION","q"),reason:"Ajustar",revisionInstructions:["Reduzir"]})).state,"REVISION_REQUESTED");assert.equal(await count("editorial_revision_requests"),1);assert.equal(await count("editorial_drafts"),1)});
 test("creates a revised version and preserves the source",async()=>{const x=await seed("revise"),s=service();await s.requestRevision({...cmd(x,"REQUEST_REVISION","q"),reason:"Ajustar",revisionInstructions:["Reduzir"]});const p=(await new PostgresHumanEditorialReviewRepository(pool).get(x.draftId))!;const r=await s.submitRevision({draftId:x.draftId,reviewerId:"andre-local",revision:{title:"Título revisado",body:p.draft.body,acknowledgedInstructions:["Reduzir"]},reviewedAt:x.at,idempotencyKey:`revise:${x.draftId}`});assert.equal(r.state,"PENDING_APPROVAL");assert.equal(await count("editorial_drafts"),2);assert.equal((await pool.query(`SELECT status FROM editorial_revision_requests`)).rows[0].status,"FULFILLED")});
 test("accepts a localized fact and persists the complete revision lifecycle",async()=>{const x=await localizedSeed("localized-lifecycle"),r=await x.service.submitRevision(x.input);assert.equal(r.state,"PENDING_APPROVAL");assert.equal(r.validation.factPreservationMethod,"LOCALIZED_EQUIVALENT");assert.equal(r.validation.equivalenceId,"official-announcement-en-to-pt-br-v1");const drafts=await pool.query<{id:string;version_number:number;title:string}>(`SELECT id,version_number,title FROM editorial_drafts ORDER BY version_number`);assert.equal(drafts.rowCount,2);assert.equal(drafts.rows[0]?.id,x.seed.draftId);assert.equal(drafts.rows[1]?.version_number,2);assert.match(drafts.rows[1]?.title??"",/foi anunciado oficialmente/);const request=(await pool.query<{status:string;revised_version:number}>(`SELECT status,revised_version FROM editorial_revision_requests`)).rows[0];assert.equal(request?.status,"FULFILLED");assert.equal(request?.revised_version,2);const news=(await pool.query<{state:string}>(`SELECT state FROM editorial_news`)).rows[0];assert.equal(news?.state,"PENDING_APPROVAL");const actions=(await pool.query<{action:string}>(`SELECT action FROM audit_events WHERE action IN ('EDITORIAL_DRAFT_REVISED','EDITORIAL_DRAFT_RESUBMITTED') ORDER BY action`)).rows.map(row=>row.action);assert.deepEqual(actions,["EDITORIAL_DRAFT_RESUBMITTED","EDITORIAL_DRAFT_REVISED"])});
 test("records localized preservation in validation and audit metadata",async()=>{const x=await localizedSeed("localized-audit"),r=await x.service.submitRevision(x.input);const validation=(await pool.query<{evaluated_rules:unknown}>(`SELECT evaluated_rules FROM editorial_draft_validations WHERE draft_id=$1`,[r.draft.draftId])).rows[0];assert.match(JSON.stringify(validation?.evaluated_rules),/fact-preservation:LOCALIZED_EQUIVALENT/);assert.match(JSON.stringify(validation?.evaluated_rules),/official-announcement-en-to-pt-br-v1/);const events=await pool.query<{technical_payload:Record<string,string>}>(`SELECT technical_payload FROM audit_events WHERE content_version_id=$1 AND action='EDITORIAL_DRAFT_REVISED'`,[r.draft.draftId]);assert.equal(events.rows[0]?.technical_payload.factPreservationMethod,"LOCALIZED_EQUIVALENT");assert.equal(events.rows[0]?.technical_payload.equivalenceId,"official-announcement-en-to-pt-br-v1")});
 test("localized revision preserves citations and returns the original warning set",async()=>{const x=await localizedSeed("localized-citations"),r=await x.service.submitRevision(x.input),p=await new PostgresHumanEditorialReviewRepository(pool).get(r.draft.draftId);assert.equal(p?.citations.length,1);assert.deepEqual(p?.citations,x.package.citations);assert.deepEqual(p?.warnings,x.package.warnings)});
 test("replays the same localized revision without extra rows or events",async()=>{const x=await localizedSeed("localized-replay"),first=await x.service.submitRevision(x.input),drafts=await count("editorial_drafts"),events=await count("audit_events"),second=await x.service.submitRevision(x.input);assert.equal(first.replayed,false);assert.equal(second.replayed,true);assert.equal(second.draft.draftId,first.draft.draftId);assert.equal(second.validation.factPreservationMethod,"LOCALIZED_EQUIVALENT");assert.equal(await count("editorial_drafts"),drafts);assert.equal(await count("audit_events"),events)});
 test("replays a localized revision after repository reconnection",async()=>{const x=await localizedSeed("localized-reconnect"),first=await x.service.submitRevision(x.input),other=new HumanEditorialReviewService(new PostgresHumanEditorialReviewRepository(pool)),second=await other.submitRevision(x.input);assert.equal(second.replayed,true);assert.equal(second.draft.draftId,first.draft.draftId);assert.equal(await count("editorial_drafts"),2)});
 test("blocks an altered localized entity with a stable error",async()=>{const x=await localizedSeed("localized-entity"),invalid={...x.input,revision:{...x.input.revision,title:"Orbit Search foi anunciado oficialmente.",body:x.package.draft.body.replaceAll("Orbit 2.0 was officially announced.","Orbit Search foi anunciado oficialmente.")}};await assert.rejects(x.service.submitRevision(invalid),(e:HumanEditorialReviewError)=>e.code==="EDITORIAL_REVIEW_LOCALIZED_ENTITY_MISMATCH");await assertInvalidRevisionRollback()});
 test("blocks a stronger localized predicate with a stable error",async()=>{const x=await localizedSeed("localized-predicate"),invalid={...x.input,revision:{...x.input.revision,title:"Orbit 2.0 foi lançado.",body:x.package.draft.body.replaceAll("Orbit 2.0 was officially announced.","Orbit 2.0 foi lançado.")}};await assert.rejects(x.service.submitRevision(invalid),(e:HumanEditorialReviewError)=>e.code==="EDITORIAL_REVIEW_LOCALIZED_PREDICATE_UNSUPPORTED");await assertInvalidRevisionRollback()});
 test("rolls back an additional fact without a partial version or event",async()=>{const x=await localizedSeed("localized-extra"),beforeEvents=await count("audit_events"),invalid={...x.input,revision:{...x.input.revision,body:`${x.input.revision.body} Também integra outro produto.`}};await assert.rejects(x.service.submitRevision(invalid),(e:HumanEditorialReviewError)=>e.code==="EDITORIAL_REVIEW_PROHIBITED_FACT");assert.equal(await count("editorial_drafts"),1);assert.equal(await count("audit_events"),beforeEvents);assert.equal((await pool.query<{state:string}>(`SELECT state FROM editorial_news`)).rows[0]?.state,"CHANGES_REQUESTED");assert.equal((await pool.query<{status:string}>(`SELECT status FROM editorial_revision_requests`)).rows[0]?.status,"OPEN")});
 test("blocks stale versions without partial decision",async()=>{const x=await seed("stale");await assert.rejects(service().approve({...cmd(x,"APPROVE","s"),expectedNewsVersion:x.newsVersion-1}),(e:HumanEditorialReviewError)=>e.code==="EDITORIAL_REVIEW_VERSION_CONFLICT");assert.equal(await count("editorial_review_decisions"),0)});
 test("allows only one conflicting concurrent decision",async()=>{const x=await seed("race"),s=service();const a=s.approve(cmd(x,"APPROVE","one")),b=s.reject({...cmd(x,"REJECT","two"),reason:"Rejeitar"});const results=await Promise.allSettled([a,b]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal(await count("editorial_review_decisions"),1)});
 test("replay survives a new repository instance",async()=>{const x=await seed("reconnect");await service().approve(cmd(x,"APPROVE","same"));const other=new HumanEditorialReviewService(new PostgresHumanEditorialReviewRepository(pool));assert.equal((await other.approve(cmd(x,"APPROVE","same"))).replayed,true)});
});
function service(){return new HumanEditorialReviewService(new PostgresHumanEditorialReviewRepository(pool))}
function cmd(x:Awaited<ReturnType<typeof seed>>,_decision:string,suffix:string){return {reviewId:`review-${suffix}-${x.draftId}`,draftId:x.draftId,expectedDraftVersion:1,expectedNewsVersion:x.newsVersion,reviewerId:"andre-local",reviewedAt:x.at,idempotencyKey:`key-${suffix}-${x.draftId}`}}
async function seed(s:string){const f=createApprovedWorkflowFixture(`review-${s}`),editorial=new EditorialWorkflowService(new PostgresEditorialNewsRepository(pool));await editorial.execute(f.receive);for(const c of f.commands.slice(0,3))await editorial.execute(c);const at="2026-07-25T12:00:00.000Z",verificationId=`verification-review-${s}`,claimId=`claim-review-${s}`;await new VerificationWorkflowService(new PostgresVerificationRepository(pool)).evaluate({newsId:f.receive.newsId,verificationId,commandId:`vc-${s}`,idempotencyKey:`vk-${s}`,expectedVersion:3,actor:{type:"SYSTEM",id:"test"},occurredAt:at,allowedSourceIds:["official-test"],claims:[{id:claimId,text:"Orbit 2.0 was officially announced.",type:"PRODUCT_LAUNCH",importance:"PRIMARY",expectedSubject:"Orbit"}],evidence:[{id:`e-${s}`,claimId,sourceId:"official-test",canonicalUrl:"https://example.com/orbit",sourceAuthority:"PRIMARY_OFFICIAL",evidenceType:"RELEASE_NOTE",retrievedAt:at,eventDate:at,excerpt:"Orbit 2.0 was officially announced.",structuredFacts:{announced:true},supportsClaim:true,contradictsClaim:false}]});const result=await new EditorialDraftWorkflowService(new PostgresEditorialDraftRepository(pool)).createDraft({newsId:f.receive.newsId,verificationId,format:"WEBSITE_NEWS_BRIEF",idempotencyKey:`dk-${s}`,commandId:`dc-${s}`,approvalRequestId:`ap-${s}`,expectedVersion:4,actor:{type:"SYSTEM",id:"test"},occurredAt:at});const news=await new PostgresEditorialNewsRepository(pool).getById(f.receive.newsId);return {draftId:result.draft.draftId,newsVersion:news.auditEvents.length,at}}
async function localizedSeed(s:string){const seeded=await seed(s),reviewService=service();await reviewService.requestRevision({...cmd(seeded,"REQUEST_REVISION","localized"),reason:"Traduzir",revisionInstructions:["Traduzir somente o predicado."]});const pkg=(await new PostgresHumanEditorialReviewRepository(pool).get(seeded.draftId))!,source="Orbit 2.0 was officially announced.",target="Orbit 2.0 foi anunciado oficialmente.";return {seed:seeded,service:reviewService,package:pkg,input:{draftId:seeded.draftId,reviewerId:"andre-local",revision:{title:pkg.draft.title.replaceAll(source,target),...(pkg.draft.subtitle?{subtitle:pkg.draft.subtitle}:{}),body:pkg.draft.body.replaceAll(source,target),acknowledgedInstructions:["Traduzir somente o predicado."]},reviewedAt:"2026-07-25T12:01:00.000Z",idempotencyKey:`localized-revise:${seeded.draftId}`}}}
async function assertInvalidRevisionRollback(){assert.equal(await count("editorial_drafts"),1);assert.equal((await pool.query<{state:string}>(`SELECT state FROM editorial_news`)).rows[0]?.state,"CHANGES_REQUESTED");assert.equal((await pool.query<{status:string}>(`SELECT status FROM editorial_revision_requests`)).rows[0]?.status,"OPEN");assert.equal((await pool.query<{count:string}>(`SELECT count(*) FROM audit_events WHERE action IN ('EDITORIAL_DRAFT_REVISED','EDITORIAL_DRAFT_RESUBMITTED')`)).rows[0]?.count,"0")}
async function count(table:string){const r=await pool.query<{count:string}>(`SELECT count(*) FROM ${table}`);return Number(r.rows[0]?.count??0)}
