import assert from "node:assert/strict";
import {after,before,beforeEach,describe,test} from "node:test";
import type {Pool} from "pg";
import {assertSafeTestDatabase,createDatabasePool,loadDatabaseConfig,resetTestDatabase,PostgresEditorialNewsRepository,PostgresVerificationRepository,PostgresEditorialDraftRepository,PostgresHumanEditorialReviewRepository} from "../../database/src/index.ts";
import {createApprovedWorkflowFixture,EditorialWorkflowService,VerificationWorkflowService,EditorialDraftWorkflowService,HumanEditorialReviewService,HumanEditorialReviewError} from "../src/index.ts";
const config=loadDatabaseConfig();assertSafeTestDatabase(config.database);let pool:Pool;
before(async()=>{pool=createDatabasePool(config);await resetTestDatabase(pool,config)});beforeEach(async()=>{await pool.query(`TRUNCATE editorial_revision_requests,editorial_review_decisions,editorial_draft_validations,editorial_draft_citations,editorial_drafts,editorial_brief_facts,editorial_brief_claims,editorial_briefs,verification_claim_results,verification_results,verification_evidence,verification_claims,verification_runs,approval_actions,processed_commands,audit_events,editorial_relevance_results,approval_requests,draft_versions,editorial_news CASCADE`)});after(async()=>pool.end());
describe("human editorial review with PostgreSQL",()=>{
 test("lists and recovers a complete package",async()=>{const x=await seed("list");const repo=new PostgresHumanEditorialReviewRepository(pool),p=await repo.get(x.draftId);assert.equal((await repo.listPending()).length,1);assert.equal(p?.allowedFacts.length,1);assert.equal(p?.citations.length,1);assert.equal(p?.news?.state,"PENDING_APPROVAL")});
 test("approves atomically and replays",async()=>{const x=await seed("approve"),s=service();const first=await s.approve(cmd(x,"APPROVE","a"));assert.equal(first.state,"APPROVED");const events=await count("audit_events");assert.equal((await s.approve(cmd(x,"APPROVE","a"))).replayed,true);assert.equal(await count("editorial_review_decisions"),1);assert.equal(await count("audit_events"),events)});
 test("rejects with a persisted reason",async()=>{const x=await seed("reject");assert.equal((await service().reject({...cmd(x,"REJECT","r"),reason:"Não publicar"})).state,"REJECTED");assert.equal(await count("editorial_review_decisions"),1)});
 test("requests revision without creating a version",async()=>{const x=await seed("request");assert.equal((await service().requestRevision({...cmd(x,"REQUEST_REVISION","q"),reason:"Ajustar",revisionInstructions:["Reduzir"]})).state,"REVISION_REQUESTED");assert.equal(await count("editorial_revision_requests"),1);assert.equal(await count("editorial_drafts"),1)});
 test("creates a revised version and preserves the source",async()=>{const x=await seed("revise"),s=service();await s.requestRevision({...cmd(x,"REQUEST_REVISION","q"),reason:"Ajustar",revisionInstructions:["Reduzir"]});const p=(await new PostgresHumanEditorialReviewRepository(pool).get(x.draftId))!;const r=await s.submitRevision({draftId:x.draftId,reviewerId:"andre-local",revision:{title:"Título revisado",body:p.draft.body,acknowledgedInstructions:["Reduzir"]},reviewedAt:x.at,idempotencyKey:`revise:${x.draftId}`});assert.equal(r.state,"PENDING_APPROVAL");assert.equal(await count("editorial_drafts"),2);assert.equal((await pool.query(`SELECT status FROM editorial_revision_requests`)).rows[0].status,"FULFILLED")});
 test("blocks stale versions without partial decision",async()=>{const x=await seed("stale");await assert.rejects(service().approve({...cmd(x,"APPROVE","s"),expectedNewsVersion:x.newsVersion-1}),(e:HumanEditorialReviewError)=>e.code==="EDITORIAL_REVIEW_VERSION_CONFLICT");assert.equal(await count("editorial_review_decisions"),0)});
 test("allows only one conflicting concurrent decision",async()=>{const x=await seed("race"),s=service();const a=s.approve(cmd(x,"APPROVE","one")),b=s.reject({...cmd(x,"REJECT","two"),reason:"Rejeitar"});const results=await Promise.allSettled([a,b]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal(await count("editorial_review_decisions"),1)});
 test("replay survives a new repository instance",async()=>{const x=await seed("reconnect");await service().approve(cmd(x,"APPROVE","same"));const other=new HumanEditorialReviewService(new PostgresHumanEditorialReviewRepository(pool));assert.equal((await other.approve(cmd(x,"APPROVE","same"))).replayed,true)});
});
function service(){return new HumanEditorialReviewService(new PostgresHumanEditorialReviewRepository(pool))}
function cmd(x:Awaited<ReturnType<typeof seed>>,_decision:string,suffix:string){return {reviewId:`review-${suffix}-${x.draftId}`,draftId:x.draftId,expectedDraftVersion:1,expectedNewsVersion:x.newsVersion,reviewerId:"andre-local",reviewedAt:x.at,idempotencyKey:`key-${suffix}-${x.draftId}`}}
async function seed(s:string){const f=createApprovedWorkflowFixture(`review-${s}`),editorial=new EditorialWorkflowService(new PostgresEditorialNewsRepository(pool));await editorial.execute(f.receive);for(const c of f.commands.slice(0,3))await editorial.execute(c);const at="2026-07-25T12:00:00.000Z",verificationId=`verification-review-${s}`,claimId=`claim-review-${s}`;await new VerificationWorkflowService(new PostgresVerificationRepository(pool)).evaluate({newsId:f.receive.newsId,verificationId,commandId:`vc-${s}`,idempotencyKey:`vk-${s}`,expectedVersion:3,actor:{type:"SYSTEM",id:"test"},occurredAt:at,allowedSourceIds:["official-test"],claims:[{id:claimId,text:"Orbit 2.0 was officially announced.",type:"PRODUCT_LAUNCH",importance:"PRIMARY",expectedSubject:"Orbit"}],evidence:[{id:`e-${s}`,claimId,sourceId:"official-test",canonicalUrl:"https://example.com/orbit",sourceAuthority:"PRIMARY_OFFICIAL",evidenceType:"RELEASE_NOTE",retrievedAt:at,eventDate:at,excerpt:"Orbit 2.0 was officially announced.",structuredFacts:{announced:true},supportsClaim:true,contradictsClaim:false}]});const result=await new EditorialDraftWorkflowService(new PostgresEditorialDraftRepository(pool)).createDraft({newsId:f.receive.newsId,verificationId,format:"WEBSITE_NEWS_BRIEF",idempotencyKey:`dk-${s}`,commandId:`dc-${s}`,approvalRequestId:`ap-${s}`,expectedVersion:4,actor:{type:"SYSTEM",id:"test"},occurredAt:at});const news=await new PostgresEditorialNewsRepository(pool).getById(f.receive.newsId);return {draftId:result.draft.draftId,newsVersion:news.auditEvents.length,at}}
async function count(table:string){const r=await pool.query<{count:string}>(`SELECT count(*) FROM ${table}`);return Number(r.rows[0]?.count??0)}
