import assert from "node:assert/strict";
import {after,before,beforeEach,describe,test} from "node:test";
import {mkdtemp,rm} from "node:fs/promises";import {join} from "node:path";import {tmpdir} from "node:os";import type {Pool} from "pg";
import {assertSafeTestDatabase,createDatabasePool,loadDatabaseConfig,resetTestDatabase,PostgresEditorialNewsRepository,PostgresVerificationRepository,PostgresEditorialDraftRepository,PostgresHumanEditorialReviewRepository,PostgresPublicationPackageRepository} from "../../database/src/index.ts";
import {createApprovedWorkflowFixture,EditorialWorkflowService,VerificationWorkflowService,EditorialDraftWorkflowService,HumanEditorialReviewService,LocalPublicationExporter,PublicationPackageService,PublicationPackageError} from "../src/index.ts";
const config=loadDatabaseConfig();assertSafeTestDatabase(config.database);let pool:Pool;let roots:string[]=[];
before(async()=>{pool=createDatabasePool(config);await resetTestDatabase(pool,config)});beforeEach(async()=>{await pool.query(`TRUNCATE publication_package_citations,publication_package_files,publication_packages,editorial_revision_requests,editorial_review_decisions,editorial_draft_validations,editorial_draft_citations,editorial_drafts,editorial_brief_facts,editorial_brief_claims,editorial_briefs,verification_claim_results,verification_results,verification_evidence,verification_claims,verification_runs,approval_actions,processed_commands,audit_events,editorial_relevance_results,approval_requests,draft_versions,editorial_news CASCADE`);for(const r of roots)await rm(r,{recursive:true,force:true});roots=[]});after(async()=>{for(const r of roots)await rm(r,{recursive:true,force:true});await pool.end()});
describe("publication packages with PostgreSQL",()=>{
 test("lists only approved drafts",async()=>{const x=await approved("eligible"),repo=new PostgresPublicationPackageRepository(pool);assert.equal((await repo.listEligible()).length,1);assert.equal((await repo.loadApproved(x.draftId))?.reviewerId,"andre-local")});
 test("exports and reaches READY_FOR_PUBLICATION",async()=>{const x=await approved("export"),s=await service();const r=await s.exportPackage(input(x,"WEBSITE_EXPORT"));assert.equal(r.pkg.status,"READY_FOR_PUBLICATION");assert.equal((await new PostgresEditorialNewsRepository(pool).getById(x.newsId)).state,"READY_FOR_PUBLICATION");assert.equal(await count("publication_package_files"),3);assert.equal(await count("publication_package_citations"),1)});
 test("replays after a new service instance without extra events",async()=>{const x=await approved("replay"),s=await service(),i=input(x,"LINKEDIN_EXPORT");await s.exportPackage(i);const events=await count("audit_events"),other=new PublicationPackageService(new PostgresPublicationPackageRepository(pool),new LocalPublicationExporter(i.root));assert.equal((await other.exportPackage(i)).replayed,true);assert.equal(await count("publication_packages"),1);assert.equal(await count("audit_events"),events)});
 test("blocks a pending draft without files or rows",async()=>{const x=await drafted("pending"),s=await service();await assert.rejects(s.exportPackage(input(x,"WEBSITE_EXPORT")),(e:PublicationPackageError)=>e.code==="PUBLICATION_PACKAGE_DRAFT_NOT_FOUND");assert.equal(await count("publication_packages"),0)});
 test("rejects a stale approved version transactionally",async()=>{const x=await approved("stale"),repo=new PostgresPublicationPackageRepository(pool),context=(await repo.loadApproved(x.draftId))!;const {buildPublicationPackage}=await import("../src/publication-package-service.ts"),pkg=buildPublicationPackage(context,"WEBSITE_EXPORT","2026-07-27T14:00:00.000Z");await pool.query(`UPDATE editorial_news SET lock_version=lock_version+1 WHERE id=$1`,[x.newsId]);await assert.rejects(repo.save({pkg,files:[],idempotencyKey:"stale-key",commandId:"stale-command"}),(e:PublicationPackageError)=>e.code==="PUBLICATION_PACKAGE_VERSION_MISMATCH");assert.equal(await count("publication_packages"),0)});
});
async function service(){const root=await mkdtemp(join(tmpdir(),"publication-pg-"));roots.push(root);return new PublicationPackageService(new PostgresPublicationPackageRepository(pool),new LocalPublicationExporter(root))}
function input(x:{draftId:string;newsId:string;newsVersion:number},destination:"LINKEDIN_EXPORT"|"WEBSITE_EXPORT"){const root=roots.at(-1)!;return {draftId:x.draftId,destination,reviewerId:"andre-local",createdAt:"2026-07-27T14:00:00.000Z",idempotencyKey:`publication:${x.draftId}:${destination}`,commandId:`publication:${x.draftId}:${destination}`,root}}
async function approved(s:string){const x=await drafted(s),review=new HumanEditorialReviewService(new PostgresHumanEditorialReviewRepository(pool));await review.approve({reviewId:`review-${s}`,draftId:x.draftId,expectedDraftVersion:1,expectedNewsVersion:x.newsVersion,reviewerId:"andre-local",reviewedAt:"2026-07-27T13:00:00.000Z",idempotencyKey:`review-${s}`});const news=await new PostgresEditorialNewsRepository(pool).getById(x.newsId);return {...x,newsVersion:news.auditEvents.length}}
async function drafted(s:string){const f=createApprovedWorkflowFixture(`publication-${s}`),editorial=new EditorialWorkflowService(new PostgresEditorialNewsRepository(pool));await editorial.execute(f.receive);for(const c of f.commands.slice(0,3))await editorial.execute(c);const at="2026-07-27T12:00:00.000Z",verificationId=`pv-${s}`,claimId=`pc-${s}`;await new VerificationWorkflowService(new PostgresVerificationRepository(pool)).evaluate({newsId:f.receive.newsId,verificationId,commandId:`pvc-${s}`,idempotencyKey:`pvk-${s}`,expectedVersion:3,actor:{type:"SYSTEM",id:"test"},occurredAt:at,allowedSourceIds:["official-test"],claims:[{id:claimId,text:"Orbit 2.0 was officially announced.",type:"PRODUCT_LAUNCH",importance:"PRIMARY",expectedSubject:"Orbit"}],evidence:[{id:`pe-${s}`,claimId,sourceId:"official-test",canonicalUrl:"https://example.com/orbit",sourceAuthority:"PRIMARY_OFFICIAL",evidenceType:"RELEASE_NOTE",retrievedAt:at,eventDate:at,excerpt:"Orbit 2.0 was officially announced.",structuredFacts:{announced:true},supportsClaim:true,contradictsClaim:false}]});const d=await new EditorialDraftWorkflowService(new PostgresEditorialDraftRepository(pool)).createDraft({newsId:f.receive.newsId,verificationId,format:"WEBSITE_NEWS_BRIEF",idempotencyKey:`pdk-${s}`,commandId:`pdc-${s}`,approvalRequestId:`pap-${s}`,expectedVersion:4,actor:{type:"SYSTEM",id:"test"},occurredAt:at});const news=await new PostgresEditorialNewsRepository(pool).getById(f.receive.newsId);return {draftId:d.draft.draftId,newsId:f.receive.newsId,newsVersion:news.auditEvents.length}}
async function count(table:string){const r=await pool.query<{count:string}>(`SELECT count(*) FROM ${table}`);return Number(r.rows[0]?.count??0)}
