import assert from "node:assert/strict";
import {after,before,beforeEach,describe,test} from "node:test";
import {mkdtemp,rm,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import type {Pool} from "pg";
import {assertSafeTestDatabase,createDatabasePool,loadDatabaseConfig,resetTestDatabase,PostgresEditorialNewsRepository,PostgresVerificationRepository,PostgresEditorialDraftRepository,PostgresHumanEditorialReviewRepository,PostgresPublicationPackageRepository,PostgresWebsitePublicationPlanRepository} from "../../database/src/index.ts";
import {createApprovedWorkflowFixture,EditorialWorkflowService,VerificationWorkflowService,EditorialDraftWorkflowService,HumanEditorialReviewService,LocalPublicationExporter,PublicationPackageService,LocalWebsitePublicationPackageReader,WebsitePublicationPlanningError,WebsitePublicationPlanningService,type WebsiteTargetProfile} from "../src/index.ts";

const config=loadDatabaseConfig();assertSafeTestDatabase(config.database);let pool:Pool;const roots:string[]=[];
const legacyProfile:WebsiteTargetProfile={targetId:"andrestudio-website",profileVersion:"andre-studio-website-target-v1",brand:"AndréStudio.dev",publicBaseUrl:"https://andrestudiodev.duckdns.org",legacyTechnicalBaseUrl:"https://andrestudiodev.duckdns.org",publicationMode:"STATIC_MARKDOWN",contentDirectory:"content/news",assetDirectory:"UNKNOWN",routePattern:"/noticias/<slug>",requiresBuild:true,requiresRestart:"UNKNOWN",policyId:"andre-studio-website-publication",policyVersion:"andre-studio-website-publication-v1"};
before(async()=>{pool=createDatabasePool(config);await resetTestDatabase(pool,config)});
beforeEach(async()=>{await pool.query(`TRUNCATE website_publication_plan_prerequisites,website_publication_plan_operations,website_publication_plans,publication_package_citations,publication_package_files,publication_packages,editorial_revision_requests,editorial_review_decisions,editorial_draft_validations,editorial_draft_citations,editorial_drafts,editorial_brief_facts,editorial_brief_claims,editorial_briefs,verification_claim_results,verification_results,verification_evidence,verification_claims,verification_runs,approval_actions,processed_commands,audit_events,editorial_relevance_results,approval_requests,draft_versions,editorial_news CASCADE`);for(const root of roots.splice(0))await rm(root,{recursive:true,force:true})});
after(async()=>{for(const root of roots)await rm(root,{recursive:true,force:true});await pool.end()});
describe("website publication plans with PostgreSQL",()=>{
 test("persists profile v2, operations, prerequisites and three audit events",async()=>{const x=await ready("persist"),result=await x.service.createDryRunPlan(x.input);assert.equal(result.plan.status,"DRY_RUN_COMPLETED");assert.equal(result.plan.profileVersion,"andre-studio-website-target-v2");assert.equal(result.plan.publicBaseUrl,"https://andrestudio.dev.br");assert.equal(result.plan.publicationStrategy,"UNKNOWN");assert.equal(await count("website_publication_plans"),1);assert.equal(await count("website_publication_plan_operations"),10);assert.equal(await count("website_publication_plan_prerequisites"),15);assert.equal(await planEvents(result.plan.planId),3)});
 test("replays after reconnect without rows or events",async()=>{const x=await ready("reconnect"),first=await x.service.createDryRunPlan(x.input),events=await planEvents(first.plan.planId);await pool.end();pool=createDatabasePool(config);const replay=await new WebsitePublicationPlanningService(new PostgresWebsitePublicationPlanRepository(pool),new LocalWebsitePublicationPackageReader(x.root)).createDryRunPlan(x.input);assert.equal(replay.replayed,true);assert.equal(await count("website_publication_plans"),1);assert.equal(await planEvents(first.plan.planId),events)});
 test("does not change the publication package or editorial state",async()=>{const x=await ready("state"),beforePackage=await new PostgresPublicationPackageRepository(pool).get(x.publicationId),beforeNews=await new PostgresEditorialNewsRepository(pool).getById(x.newsId);await x.service.createDryRunPlan(x.input);const afterPackage=await new PostgresPublicationPackageRepository(pool).get(x.publicationId),afterNews=await new PostgresEditorialNewsRepository(pool).getById(x.newsId);assert.equal(afterPackage?.status,"READY_FOR_PUBLICATION");assert.equal(afterPackage?.contentHash,beforePackage?.contentHash);assert.equal(afterNews.state,beforeNews.state);assert.equal(afterNews.auditEvents.length,beforeNews.auditEvents.length+3)});
 test("blocks LIVE with no persistence",async()=>{const x=await ready("live");await assert.rejects(x.service.createDryRunPlan({...x.input,mode:"LIVE"}),(e:WebsitePublicationPlanningError)=>e.code==="WEBSITE_PUBLICATION_LIVE_MODE_DISABLED");assert.equal(await count("website_publication_plans"),0)});
 test("rolls back completely on a persistence conflict",async()=>{const x=await ready("conflict");await x.service.createDryRunPlan(x.input);await assert.rejects(x.service.createDryRunPlan({...x.input,idempotencyKey:"other-key",commandId:"other-command"}),(e:WebsitePublicationPlanningError)=>e.code==="WEBSITE_PUBLICATION_PLAN_CONFLICT");assert.equal(await count("website_publication_plans"),1);assert.equal(await count("website_publication_plan_operations"),10);assert.equal(await planEvents((await x.service.listPlans())[0]!.planId),3)});
 test("rejects a tampered local package without database side effects",async()=>{const x=await ready("tamper");const source=await new PostgresWebsitePublicationPlanRepository(pool).loadReadyPackage(x.publicationId),markdown=source!.files.find(f=>f.role==="CONTENT_MARKDOWN")!;await writeFile(join(x.root,markdown.relativePath),"tampered");await assert.rejects(x.service.createDryRunPlan(x.input),(e:WebsitePublicationPlanningError)=>e.code==="WEBSITE_PUBLICATION_PACKAGE_INVALID");assert.equal(await count("website_publication_plans"),0);assert.equal(await planEvents("missing"),0)});
 test("recovers a complete plan",async()=>{const x=await ready("recover"),created=await x.service.createDryRunPlan(x.input),recovered=await x.service.getPlan(created.plan.planId);assert.equal(recovered?.functionalFingerprint,created.plan.functionalFingerprint);assert.equal(recovered?.sourceFiles.length,3);assert.equal(recovered?.operations.length,10);assert.equal(recovered?.prerequisites.length,15);assert.equal(recovered?.requiresBuild,"UNKNOWN")});
 test("allows only one concurrent plan for the same functional identity",async()=>{const x=await ready("concurrent"),results=await Promise.allSettled([x.service.createDryRunPlan(x.input),x.service.createDryRunPlan({...x.input,idempotencyKey:"concurrent-other",commandId:"concurrent-other"})]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal(results.filter(r=>r.status==="rejected"&&(r.reason as WebsitePublicationPlanningError).code==="WEBSITE_PUBLICATION_PLAN_CONFLICT").length,1);assert.equal(await count("website_publication_plans"),1);assert.equal(await count("website_publication_plan_operations"),10)});
 test("blocks a package no longer ready",async()=>{const x=await ready("not-ready");await pool.query(`UPDATE publication_packages SET status='VALIDATED' WHERE id=$1`,[x.publicationId]);await assert.rejects(x.service.createDryRunPlan(x.input),(e:WebsitePublicationPlanningError)=>e.code==="WEBSITE_PUBLICATION_PACKAGE_NOT_READY");assert.equal(await count("website_publication_plans"),0)});
 test("blocks a non-website destination",async()=>{const x=await ready("destination");await pool.query(`UPDATE publication_packages SET destination='LINKEDIN_EXPORT' WHERE id=$1`,[x.publicationId]);await assert.rejects(x.service.createDryRunPlan(x.input),(e:WebsitePublicationPlanningError)=>e.code==="WEBSITE_PUBLICATION_PACKAGE_NOT_READY");assert.equal(await count("website_publication_plans"),0)});
 test("preserves legacy plan and persists a distinct canonical-domain plan",async()=>{const x=await ready("profiles"),repo=new PostgresWebsitePublicationPlanRepository(pool),reader=new LocalWebsitePublicationPackageReader(x.root),oldService=new WebsitePublicationPlanningService(repo,reader,legacyProfile),old=(await oldService.createDryRunPlan({...x.input,idempotencyKey:"legacy-profile",commandId:"legacy-profile"})).plan,current=(await x.service.createDryRunPlan({...x.input,idempotencyKey:"current-profile",commandId:"current-profile"})).plan;assert.notEqual(old.planId,current.planId);assert.equal((await x.service.listPlans()).length,2);assert.equal((await x.service.getPlan(old.planId))?.publicBaseUrl,"https://andrestudiodev.duckdns.org");assert.equal((await x.service.getPlan(current.planId))?.publicBaseUrl,"https://andrestudio.dev.br");assert.equal((await new PostgresPublicationPackageRepository(pool).get(x.publicationId))?.status,"READY_FOR_PUBLICATION")});
});
async function ready(suffix:string){const drafted=await createDraft(suffix),review=new HumanEditorialReviewService(new PostgresHumanEditorialReviewRepository(pool));await review.approve({reviewId:`wp-review-${suffix}`,draftId:drafted.draftId,expectedDraftVersion:1,expectedNewsVersion:drafted.newsVersion,reviewerId:"andre-local",reviewedAt:"2026-07-28T10:00:00.000Z",idempotencyKey:`wp-review-${suffix}`});const approved=await new PostgresEditorialNewsRepository(pool).getById(drafted.newsId),root=await mkdtemp(join(tmpdir(),"website-plan-pg-"));roots.push(root);const publication=new PublicationPackageService(new PostgresPublicationPackageRepository(pool),new LocalPublicationExporter(root)),exported=await publication.exportPackage({draftId:drafted.draftId,destination:"WEBSITE_EXPORT",reviewerId:"andre-local",createdAt:"2026-07-28T11:00:00.000Z",idempotencyKey:`wp-publication-${suffix}`,commandId:`wp-publication-${suffix}`}),repo=new PostgresWebsitePublicationPlanRepository(pool),service=new WebsitePublicationPlanningService(repo,new LocalWebsitePublicationPackageReader(root)),input={publicationId:exported.pkg.publicationId,mode:"DRY_RUN" as const,createdAt:"2026-07-28T12:00:00.000Z",idempotencyKey:`wp-plan-${suffix}`,commandId:`wp-plan-${suffix}`};return {root,service,input,publicationId:exported.pkg.publicationId,newsId:drafted.newsId,approved}}
async function createDraft(suffix:string){const fixture=createApprovedWorkflowFixture(`website-plan-${suffix}`),editorial=new EditorialWorkflowService(new PostgresEditorialNewsRepository(pool));await editorial.execute(fixture.receive);for(const command of fixture.commands.slice(0,3))await editorial.execute(command);const at="2026-07-28T09:00:00.000Z",verificationId=`wp-verification-${suffix}`,claimId=`wp-claim-${suffix}`;await new VerificationWorkflowService(new PostgresVerificationRepository(pool)).evaluate({newsId:fixture.receive.newsId,verificationId,commandId:`wp-v-command-${suffix}`,idempotencyKey:`wp-v-key-${suffix}`,expectedVersion:3,actor:{type:"SYSTEM",id:"test"},occurredAt:at,allowedSourceIds:["official-test"],claims:[{id:claimId,text:"Orbit 2.0 was officially announced.",type:"PRODUCT_LAUNCH",importance:"PRIMARY",expectedSubject:"Orbit"}],evidence:[{id:`wp-evidence-${suffix}`,claimId,sourceId:"official-test",canonicalUrl:"https://example.com/orbit",sourceAuthority:"PRIMARY_OFFICIAL",evidenceType:"RELEASE_NOTE",retrievedAt:at,eventDate:at,excerpt:"Orbit 2.0 was officially announced.",structuredFacts:{announced:true},supportsClaim:true,contradictsClaim:false}]});const draft=await new EditorialDraftWorkflowService(new PostgresEditorialDraftRepository(pool)).createDraft({newsId:fixture.receive.newsId,verificationId,format:"WEBSITE_NEWS_BRIEF",idempotencyKey:`wp-draft-key-${suffix}`,commandId:`wp-draft-command-${suffix}`,approvalRequestId:`wp-approval-${suffix}`,expectedVersion:4,actor:{type:"SYSTEM",id:"test"},occurredAt:at}),news=await new PostgresEditorialNewsRepository(pool).getById(fixture.receive.newsId);return {draftId:draft.draft.draftId,newsId:fixture.receive.newsId,newsVersion:news.auditEvents.length}}
async function count(table:string){return Number((await pool.query<{count:string}>(`SELECT count(*) FROM ${table}`)).rows[0]?.count??0)}
async function planEvents(planId:string){return Number((await pool.query<{count:string}>(`SELECT count(*) FROM audit_events WHERE technical_payload->>'planId'=$1`,[planId])).rows[0]?.count??0)}
