import type { RelevancePolicy } from "./relevance-types.ts";

export const ANDRE_STUDIO_RELEVANCE_POLICY_V1 = {
  id: "andre-studio-relevance",
  version: "andre-studio-relevance-v1",
  weights: {
    TOPIC_AFFINITY: 30,
    SOURCE_AUTHORITY: 15,
    FRESHNESS: 20,
    TECHNICAL_IMPACT: 15,
    COMMERCIAL_POTENTIAL: 10,
    CONTENT_POTENTIAL: 10,
  },
  sourceScores: {
    OFFICIAL: 15,
    DOCUMENTATION: 13,
    REPUTABLE_TECH_MEDIA: 11,
    COMMUNITY: 6,
    UNKNOWN: 0,
  },
  noveltyScores: {
    NEW_PRODUCT: 12,
    NEW_MODEL: 15,
    MAJOR_UPDATE: 13,
    API_CHANGE: 14,
    VULNERABILITY: 15,
    DISCONTINUATION: 13,
    PRICE_CHANGE: 11,
    PLATFORM_RULE_CHANGE: 12,
    TUTORIAL: 4,
    OPINION: 2,
    NO_CONCRETE_NOVELTY: 0,
  },
  contentFormatScores: {
    POST: 2,
    ARTICLE: 3,
    VIDEO: 2,
    TUTORIAL: 4,
    DEMONSTRATION: 4,
    TECHNICAL_OPINION: 3,
  },
  commercialRelationScores: {
    AUTOMATION_SERVICE: 3,
    WEBSITE_SERVICE: 2,
    CUSTOM_SYSTEM: 3,
    APPLIED_AI: 3,
    CONSULTING: 2,
    LEAD_GENERATION: 2,
    SMALL_BUSINESS_TOOLS: 2,
  },
  penaltyPoints: {
    probablyDuplicate: 20,
    similarContent: 10,
    unknownSource: 5,
    missingEventDate: 5,
    sensationalistTitle: 8,
    unconfirmedRumor: 20,
    purelyPromotional: 10,
    lowBrandAffinity: 8,
    oldNewsPresentedAsCurrent: 15,
    noConcreteNovelty: 8,
  },
  thresholds: {
    criticalMin: 85,
    highMin: 70,
    mediumMin: 50,
    lowMin: 30,
    verificationMin: 50,
    duplicateSimilarity: 0.75,
    probableDuplicateSimilarity: 0.9,
    oldEventDays: 90,
    recentPresentationDays: 14,
  },
  topics: [
    {
      id: "artificial_intelligence",
      aliases: ["inteligencia artificial", "ia aplicada", "artificial intelligence"],
    },
    {
      id: "ai_agents",
      aliases: ["agente de ia", "agentes de ia", "ai agent", "agentic"],
    },
    {
      id: "automation",
      aliases: ["automacao", "automatizacao", "workflow automatico"],
    },
    {
      id: "web_development",
      aliases: ["desenvolvimento web", "aplicacao web", "web development"],
    },
    { id: "react", aliases: ["react"] },
    { id: "typescript", aliases: ["typescript"] },
    { id: "javascript", aliases: ["javascript"] },
    { id: "nodejs", aliases: ["node.js", "nodejs"] },
    { id: "aws", aliases: ["aws", "amazon web services"] },
    { id: "cloudflare", aliases: ["cloudflare"] },
    { id: "github", aliases: ["github"] },
    { id: "apis", aliases: ["api", "apis", "interface de programacao"] },
    { id: "saas", aliases: ["saas", "software como servico"] },
    { id: "micro_saas", aliases: ["micro-saas", "micro saas"] },
    {
      id: "developer_productivity",
      aliases: ["produtividade para desenvolvedores", "developer productivity"],
    },
    {
      id: "small_business_tools",
      aliases: ["ferramentas para pequenas empresas", "small business tools"],
    },
    {
      id: "ai_marketing",
      aliases: ["marketing com ia", "ai marketing"],
    },
    { id: "crm", aliases: ["crm", "gestao de relacionamento"] },
    {
      id: "lead_generation",
      aliases: ["captacao de leads", "geracao de leads", "lead generation"],
    },
    {
      id: "content_creation_publishing",
      aliases: ["criacao de conteudo", "publicacao de conteudo", "content creation"],
    },
    {
      id: "application_security",
      aliases: ["seguranca em aplicacoes", "application security", "appsec"],
    },
    {
      id: "new_ai_models",
      aliases: ["novo modelo de ia", "novos modelos de ia", "new ai model"],
    },
  ],
} as const satisfies RelevancePolicy;
