import {mkdtemp,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {buildPublicationPackage,InMemoryWebsitePublicationPlanRepository,LocalPublicationExporter,LocalWebsitePublicationPackageReader,WebsitePublicationPlanningService,type PublicationContext} from "../../../packages/application/src/index.ts";

const root=await mkdtemp(join(tmpdir(),"website-plan-demo-"));
try{
 const context:PublicationContext={newsId:"demo-news",newsVersion:1,newsState:"APPROVED",draftVersion:1,approvalDecisionId:"demo-approval",reviewerId:"andre-local",approvedAt:"2026-07-28T10:00:00.000Z",draft:{draftId:"demo-draft",newsId:"demo-news",briefId:"demo-brief",format:"WEBSITE_NEWS_BRIEF",language:"pt-BR",title:"Demonstração segura",body:"Conteúdo factual aprovado.",sourceCitations:[{evidenceId:"demo-evidence",claimId:"demo-claim",sourceId:"official",canonicalUrl:"https://example.com/official",title:"Fonte oficial"}],warnings:[],prohibitedClaimsChecked:true,validationStatus:"VALID",generatorId:"deterministic",generatorVersion:"v1",createdAt:"2026-07-28T09:00:00.000Z"}};
 const pkg={...buildPublicationPackage(context,"WEBSITE_EXPORT","2026-07-28T11:00:00.000Z"),status:"READY_FOR_PUBLICATION" as const},exported=await new LocalPublicationExporter(root).export(pkg),source={pkg,files:exported.files.map(({content,...file})=>file)},repo=new InMemoryWebsitePublicationPlanRepository([source]),service=new WebsitePublicationPlanningService(repo,new LocalWebsitePublicationPackageReader(root)),input={publicationId:pkg.publicationId,mode:"DRY_RUN" as const,createdAt:"2026-07-28T12:00:00.000Z",idempotencyKey:"demo-plan",commandId:"demo-plan"},first=await service.createDryRunPlan(input),replay=await service.createDryRunPlan(input);
 console.log(JSON.stringify({planId:first.plan.planId,status:first.plan.status,mode:first.plan.mode,publicUrl:first.plan.provisionalPublicUrl,publicationStrategy:first.plan.publicationStrategy,routePattern:first.plan.routePattern,requiresBuild:first.plan.requiresBuild,blockedRemoteOperations:first.plan.operations.filter(x=>x.remote&&x.status==="BLOCKED_IN_DRY_RUN").length,conditionalLocalOperations:first.plan.operations.filter(x=>!x.remote&&x.status==="REQUIRES_TARGET_INSPECTION").length,replay:replay.replayed,remoteWrites:0,packageStatus:pkg.status},null,2));
}finally{await rm(root,{recursive:true,force:true})}
