import {parseArgs} from "node:util";
import {LocalPublicationExporter,PublicationPackageService,type PublicationDestination} from "../../../packages/application/src/index.ts";
import {createDatabasePool,loadDatabaseConfig,PostgresPublicationPackageRepository} from "../../../packages/database/src/index.ts";
const action=process.argv[2],{values}=parseArgs({args:process.argv.slice(3),options:{draft:{type:"string"},destination:{type:"string"},reviewer:{type:"string"},publication:{type:"string"}},strict:true}),pool=createDatabasePool(loadDatabaseConfig()),repo=new PostgresPublicationPackageRepository(pool),service=new PublicationPackageService(repo,new LocalPublicationExporter("output"));
try{
 if(action==="list-eligible"){const rows=await service.listEligibleDrafts();if(!rows.length)console.log("Nenhum draft APPROVED elegível.");for(const x of rows)console.log(`${x.draft.draftId.slice(0,16)} | v${x.draftVersion} | ${x.draft.title} | aprovado por ${x.reviewerId}`)}
 else if(action==="preview"){if(!values.draft||!values.destination)throw new Error("PUBLICATION_PACKAGE_INPUT_INVALID");const p=await service.getPublicationPreview(values.draft,values.destination as PublicationDestination,new Date().toISOString());console.log(JSON.stringify({publicationId:p.publicationId,destination:p.destination,title:p.title,contentHash:p.contentHash,warnings:p.warnings,paths:p.destination==="LINKEDIN_EXPORT"?[`output/linkedin/${p.publicationId}.md`,`output/linkedin/${p.publicationId}.json`]:[`output/website/${p.slug}.md`,`output/website/${p.slug}.json`],manifest:`output/manifests/${p.publicationId}.json`,effects:0},null,2))}
 else if(action==="export"){if(!values.draft||!values.destination||!values.reviewer)throw new Error("PUBLICATION_PACKAGE_INPUT_INVALID");const key=`publication:${values.draft}:${values.destination}:${values.reviewer}`;console.log(JSON.stringify(await service.exportPackage({draftId:values.draft,destination:values.destination as PublicationDestination,reviewerId:values.reviewer,createdAt:new Date().toISOString(),idempotencyKey:key,commandId:key}),null,2))}
 else if(action==="list"){const rows=await service.listPublicationPackages();if(!rows.length)console.log("Nenhum pacote local persistido.");for(const p of rows)console.log(`${p.publicationId} | ${p.destination} | ${p.status}`)}
 else if(action==="show"){if(!values.publication)throw new Error("PUBLICATION_PACKAGE_INPUT_INVALID");console.log(JSON.stringify(await service.getPublicationPackage(values.publication),null,2))}
 else throw new Error("PUBLICATION_PACKAGE_COMMAND_INVALID");
}finally{await pool.end()}
