import { createHash } from "node:crypto";
import type { Pool, PoolClient, QueryResultRow } from "pg";
import type { HumanReviewInput, HumanReviewRepository, EditorialReviewPackage, ManualDraftRevision, ReviewDecision, HumanReviewState } from "../../application/src/human-editorial-review-service.ts";
import { HumanEditorialReviewError } from "../../application/src/human-editorial-review-service.ts";
import type { EditorialBrief, EditorialDraft } from "../../content-engine/src/editorial-drafting.ts";
import { validateEditorialDraft } from "../../content-engine/src/editorial-drafting.ts";
import { withTransaction } from "./client.ts";

const POLICY_ID="andre-studio-human-review", POLICY_VERSION="andre-studio-human-review-v1";
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");

export class PostgresHumanEditorialReviewRepository implements HumanReviewRepository {
  private readonly pool:Pool; constructor(pool:Pool){this.pool=pool}
  async listPending(){const r=await this.pool.query<{id:string}>(`SELECT d.id FROM editorial_drafts d JOIN editorial_news n ON n.id=d.news_id WHERE n.state='PENDING_APPROVAL' AND n.current_draft_version_id=d.id ORDER BY d.created_at,d.id`);return (await Promise.all(r.rows.map(x=>this.get(x.id)))).filter((x):x is EditorialReviewPackage=>x!==undefined)}
  async get(id:string):Promise<EditorialReviewPackage|undefined>{
    const r=await this.pool.query<QueryResultRow>(`SELECT d.*,b.*,d.id draft_id,d.created_at draft_created_at,n.title news_title,n.state news_state,
      n.source,n.lock_version,v.warnings validation_warnings,v.blocking_reasons,
      COALESCE((SELECT jsonb_agg(jsonb_build_object('factId',f.id,'claimId',f.claim_id,'statement',f.statement,'confidence',f.confidence,'restrictions',f.restrictions,'evidenceIds',f.evidence_ids)) FROM editorial_brief_facts f WHERE f.brief_id=b.id),'[]') facts,
      COALESCE((SELECT jsonb_agg(jsonb_build_object('evidenceId',c.evidence_id,'claimId',c.claim_id,'sourceId',c.source_id,'canonicalUrl',c.canonical_url,'title',c.page_title,'publishedAt',c.published_at)) FROM editorial_draft_citations c WHERE c.draft_id=d.id),'[]') citations
      FROM editorial_drafts d JOIN editorial_briefs b ON b.id=d.brief_id JOIN editorial_news n ON n.id=d.news_id JOIN editorial_draft_validations v ON v.draft_id=d.id WHERE d.id=$1`,[id]);
    const x=r.rows[0];if(!x)return undefined;
    const citations=x.citations as EditorialDraft["sourceCitations"], warnings=x.validation_warnings as EditorialDraft["warnings"];
    const draft={draftId:x.draft_id,newsId:x.news_id,briefId:x.brief_id,format:x.format,language:x.language,title:x.title,body:x.body,sourceCitations:citations,warnings,prohibitedClaimsChecked:true,validationStatus:x.validation_status,generatorId:x.generator_id,generatorVersion:x.generator_version,createdAt:new Date(x.draft_created_at).toISOString(),...(x.subtitle?{subtitle:x.subtitle}:{})} as EditorialDraft;
    const brief={briefId:x.brief_id,newsId:x.news_id,verificationId:x.verification_id,relevanceScore:x.relevance_score,relevancePriority:x.relevance_priority,verificationStatus:x.verification_status,editorialEligibility:x.eligibility,policyId:x.policy_id,policyVersion:x.policy_version,createdAt:new Date(x.created_at).toISOString(),subject:x.subject,confirmedClaims:[],restrictedClaims:[],prohibitedClaims:[],evidenceReferences:citations,sourceReferences:citations,allowedFacts:x.facts,warnings,requiredDisclosures:[],prohibitedStatements:x.prohibited_statements,suggestedAngles:[],suggestedFormats:[x.format]} as EditorialBrief;
    const claimRows=await this.pool.query<QueryResultRow>(`SELECT bc.*,vc.claim_text,vc.importance FROM editorial_brief_claims bc JOIN verification_claims vc ON vc.id=bc.claim_id WHERE bc.brief_id=$1 ORDER BY bc.claim_id`,[x.brief_id]);
    const claims=claimRows.rows.map(c=>({claimId:c.claim_id,originalText:c.claim_text,normalizedText:String(c.claim_text).toLowerCase(),importance:c.importance,factualStatus:c.factual_status,confidence:c.confidence,evidenceIds:c.evidence_ids,classification:c.classification,reason:c.reason}));
    const completeBrief={...brief,confirmedClaims:claims.filter(c=>c.classification==="CONFIRMED_AND_ALLOWED"),restrictedClaims:claims.filter(c=>c.classification==="CONFIRMED_WITH_LIMITATIONS"||c.classification==="REQUIRES_HUMAN_REVIEW"),prohibitedClaims:claims.filter(c=>c.classification==="PROHIBITED")} as EditorialBrief;
    const versions=await this.pool.query<{id:string;version_number:number;created_at:Date}>(`SELECT id,version_number,created_at FROM editorial_drafts WHERE news_id=$1 AND format=$2 ORDER BY version_number`,[x.news_id,x.format]);
    const decisions=await this.pool.query<QueryResultRow>(`SELECT * FROM editorial_review_decisions WHERE news_id=$1 ORDER BY created_at,id`,[x.news_id]);
    const revisions=await this.pool.query<QueryResultRow>(`SELECT * FROM editorial_revision_requests WHERE source_draft_id IN (SELECT id FROM editorial_drafts WHERE news_id=$1) ORDER BY created_at,id`,[x.news_id]);
    return {news:{id:x.news_id,title:x.news_title,state:x.news_state,version:x.lock_version,source:x.source},draft,brief:completeBrief,allowedFacts:completeBrief.allowedFacts,prohibitedStatements:completeBrief.prohibitedStatements,evidenceReferences:citations,citations,warnings,validation:validateEditorialDraft(draft,completeBrief),versionHistory:versions.rows.map(v=>({version:v.version_number,draftId:v.id,createdAt:new Date(v.created_at).toISOString()})),reviewHistory:decisions.rows.map(toDecision),revisionRequestHistory:revisions.rows};
  }
  decide(input:HumanReviewInput){return withTransaction(this.pool,c=>decide(c,input))}
  revise(input:{draftId:string;reviewerId:string;revision:ManualDraftRevision;reviewedAt:string;idempotencyKey:string}){return withTransaction(this.pool,c=>revise(c,input))}
}
async function decide(c:PoolClient,input:HumanReviewInput):Promise<{decision:ReviewDecision;state:HumanReviewState;replayed:boolean}>{
  const {reviewedAt:_,...functional}=input;void _;const fingerprint=hash({...functional,policy:POLICY_VERSION}), prior=await c.query<QueryResultRow>(`SELECT * FROM editorial_review_decisions WHERE idempotency_key=$1 FOR UPDATE`,[input.idempotencyKey]);
  if(prior.rows[0]){if(prior.rows[0].functional_fingerprint!==fingerprint)throw new HumanEditorialReviewError("EDITORIAL_REVIEW_IDEMPOTENCY_CONFLICT","Idempotency key conflict.");return {decision:toDecision(prior.rows[0]),state:stateFor(prior.rows[0].decision),replayed:true}}
  const locked=await c.query<QueryResultRow>(`SELECT d.*,n.state,n.lock_version,n.current_draft_version_id,n.current_approval_request_id,(SELECT count(*) FROM editorial_draft_citations x WHERE x.draft_id=d.id) citation_count FROM editorial_drafts d JOIN editorial_news n ON n.id=d.news_id WHERE d.id=$1 FOR UPDATE OF n,d`,[input.draftId]);const x=locked.rows[0];
  if(!x)throw new HumanEditorialReviewError("EDITORIAL_REVIEW_DRAFT_NOT_FOUND","Draft not found.");
  if(x.state!=="PENDING_APPROVAL")throw new HumanEditorialReviewError("EDITORIAL_REVIEW_NOT_PENDING","Draft is not pending approval.");
  if(x.version_number!==input.expectedDraftVersion||x.lock_version!==input.expectedNewsVersion)throw new HumanEditorialReviewError("EDITORIAL_REVIEW_VERSION_CONFLICT","Stale expected version.");
  if(x.validation_status==="BLOCKED")throw new HumanEditorialReviewError("EDITORIAL_REVIEW_DRAFT_BLOCKED","Blocked draft.");
  if(Number(x.citation_count)<1)throw new HumanEditorialReviewError("EDITORIAL_REVIEW_CITATION_MISSING","Citation required.");
  const decisionId=input.reviewId,next=stateFor(input.decision),reason=input.reason??null;
  await c.query(`INSERT INTO editorial_review_decisions(id,draft_id,draft_version,news_id,news_version,reviewer_id,decision,reason,command_id,idempotency_key,functional_fingerprint,policy_id,policy_version,reviewed_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$14)`,[decisionId,input.draftId,input.expectedDraftVersion,x.news_id,input.expectedNewsVersion,input.reviewerId,input.decision,reason,input.reviewId,input.idempotencyKey,fingerprint,POLICY_ID,POLICY_VERSION,input.reviewedAt]);
  if(input.decision==="REQUEST_REVISION")await c.query(`INSERT INTO editorial_revision_requests(review_decision_id,id,instructions,status,source_version,source_draft_id,created_at) VALUES($1,$1,$2::jsonb,'OPEN',$3,$4,$5)`,[decisionId,JSON.stringify(input.revisionInstructions),input.expectedDraftVersion,input.draftId,input.reviewedAt]);
  await c.query(`UPDATE approval_requests SET status=$1,resolved_at=$2 WHERE id=$3`,[input.decision==="REQUEST_REVISION"?"CHANGES_REQUESTED":input.decision==="APPROVE"?"APPROVED":"REJECTED",input.reviewedAt,x.current_approval_request_id]);
  await c.query(`UPDATE editorial_news SET state=$1,lock_version=lock_version+1,updated_at=$2 WHERE id=$3`,[next==="REVISION_REQUESTED"?"CHANGES_REQUESTED":next,input.reviewedAt,x.news_id]);
  await c.query(`INSERT INTO audit_events(id,news_id,previous_state,new_state,action,actor_type,actor_id,reason,content_version_id,idempotency_key,technical_payload,occurred_at) VALUES($1,$2,'PENDING_APPROVAL',$3,$4,'HUMAN',$5,$6,$7,$8,$9::jsonb,$10)`,[`${input.reviewId}:event`,x.news_id,next,`EDITORIAL_REVIEW_${next}`,input.reviewerId,reason,input.draftId,input.idempotencyKey,JSON.stringify({policyId:POLICY_ID,policyVersion:POLICY_VERSION,commandId:input.reviewId,draftVersion:input.expectedDraftVersion}),input.reviewedAt]);
  return {decision:{reviewId:decisionId,draftId:input.draftId,draftVersion:input.expectedDraftVersion,newsVersion:input.expectedNewsVersion,reviewerId:input.reviewerId,decision:input.decision,reviewedAt:input.reviewedAt,idempotencyKey:input.idempotencyKey,...(input.reason?{reason:input.reason}:{}),...(input.revisionInstructions?{revisionInstructions:input.revisionInstructions}:{})},state:next,replayed:false}
}
async function revise(c:PoolClient,input:{draftId:string;reviewerId:string;revision:ManualDraftRevision;reviewedAt:string;idempotencyKey:string}){
 const {reviewedAt:_,...functional}=input;void _;const revisionFingerprint=hash(functional);const prior=(await c.query<QueryResultRow>(`SELECT * FROM editorial_drafts WHERE idempotency_key=$1 FOR UPDATE`,[input.idempotencyKey])).rows[0];if(prior){if(prior.command_fingerprint!==revisionFingerprint)throw new HumanEditorialReviewError("EDITORIAL_REVIEW_IDEMPOTENCY_CONFLICT","Revision idempotency conflict.");return {draft:{draftId:prior.id,newsId:prior.news_id,briefId:prior.brief_id,format:prior.format,language:prior.language,title:prior.title,body:prior.body,sourceCitations:[],warnings:[],prohibitedClaimsChecked:true,validationStatus:prior.validation_status,generatorId:prior.generator_id,generatorVersion:prior.generator_version,createdAt:new Date(prior.created_at).toISOString(),...(prior.subtitle?{subtitle:prior.subtitle}:{})} as EditorialDraft,state:"PENDING_APPROVAL" as const,replayed:true}}
 const x=(await c.query<QueryResultRow>(`SELECT d.*,n.state,n.lock_version FROM editorial_drafts d JOIN editorial_news n ON n.id=d.news_id WHERE d.id=$1 FOR UPDATE OF n,d`,[input.draftId])).rows[0];if(!x)throw new HumanEditorialReviewError("EDITORIAL_REVIEW_DRAFT_NOT_FOUND","Draft not found.");if(x.state!=="CHANGES_REQUESTED"&&x.state!=="REVISION_REQUESTED")throw new HumanEditorialReviewError("EDITORIAL_REVIEW_REVISION_NOT_REQUESTED","Revision not requested.");
 const req=(await c.query<QueryResultRow>(`SELECT * FROM editorial_revision_requests WHERE source_draft_id=$1 AND status='OPEN' FOR UPDATE`,[input.draftId])).rows[0];if(!req)throw new HumanEditorialReviewError("EDITORIAL_REVIEW_REVISION_NOT_REQUESTED","Open request missing.");
 const id=`${input.draftId}-v${Number(x.version_number)+1}`;await c.query(`INSERT INTO draft_versions(id,news_id,version_number,body,change_reason,actor_type,actor_id,based_on_version_id,created_at) VALUES($1,$2,$3,$4,'manual review','HUMAN',$5,$6,$7)`,[id,x.news_id,Number(x.version_number)+1,input.revision.body,input.reviewerId,input.draftId,input.reviewedAt]);
 await c.query(`INSERT INTO editorial_drafts(id,brief_id,news_id,idempotency_key,command_fingerprint,format,language,title,subtitle,body,generator_id,generator_version,validation_status,created_at,version_number,source_draft_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'human-review',$11,'VALID',$12,$13,$14)`,[id,x.brief_id,x.news_id,input.idempotencyKey,revisionFingerprint,x.format,x.language,input.revision.title,input.revision.subtitle??null,input.revision.body,POLICY_VERSION,input.reviewedAt,Number(x.version_number)+1,input.draftId]);
 await c.query(`INSERT INTO editorial_draft_citations SELECT $1,evidence_id,claim_id,source_id,canonical_url,page_title,published_at FROM editorial_draft_citations WHERE draft_id=$2`,[id,input.draftId]);await c.query(`INSERT INTO editorial_draft_validations SELECT $1,status,evaluated_rules,warnings,blocking_reasons,$3 FROM editorial_draft_validations WHERE draft_id=$2`,[id,input.draftId,input.reviewedAt]);
 const approval=`approval:${id}`;await c.query(`INSERT INTO approval_requests(id,news_id,draft_version_id,status,requested_at) VALUES($1,$2,$3,'PENDING',$4)`,[approval,x.news_id,id,input.reviewedAt]);await c.query(`UPDATE editorial_revision_requests SET status='FULFILLED',revised_version=$1,revised_draft_id=$2,fulfilled_at=$3 WHERE id=$4`,[Number(x.version_number)+1,id,input.reviewedAt,req.id]);
 await c.query(`UPDATE editorial_news SET state='PENDING_APPROVAL',current_draft_version_id=$1,current_approval_request_id=$2,lock_version=lock_version+2,updated_at=$3 WHERE id=$4`,[id,approval,input.reviewedAt,x.news_id]);
 for(const [suffix,action,prev,next] of [["revised","EDITORIAL_DRAFT_REVISED","REVISION_REQUESTED","DRAFT_CREATED"],["resubmitted","EDITORIAL_DRAFT_RESUBMITTED","DRAFT_CREATED","PENDING_APPROVAL"]] as const)await c.query(`INSERT INTO audit_events(id,news_id,previous_state,new_state,action,actor_type,actor_id,content_version_id,idempotency_key,technical_payload,occurred_at) VALUES($1,$2,$3,$4,$5,'HUMAN',$6,$7,$8,$9::jsonb,$10)`,[`${input.idempotencyKey}:${suffix}`,x.news_id,prev,next,action,input.reviewerId,id,input.idempotencyKey,JSON.stringify({policyId:POLICY_ID,policyVersion:POLICY_VERSION}),input.reviewedAt]);
 return {draft:{draftId:id,newsId:x.news_id,briefId:x.brief_id,format:x.format,language:x.language,title:input.revision.title,body:input.revision.body,sourceCitations:[],warnings:[],prohibitedClaimsChecked:true,validationStatus:"VALID",generatorId:"human-review",generatorVersion:POLICY_VERSION,createdAt:input.reviewedAt,...(input.revision.subtitle?{subtitle:input.revision.subtitle}:{})} as EditorialDraft,state:"PENDING_APPROVAL" as const,replayed:false}
}
function stateFor(d:string):HumanReviewState{return d==="APPROVE"?"APPROVED":d==="REJECT"?"REJECTED":"REVISION_REQUESTED"}
function toDecision(x:QueryResultRow):ReviewDecision{return {reviewId:x.id,draftId:x.draft_id,draftVersion:x.draft_version,newsVersion:x.news_version,reviewerId:x.reviewer_id,decision:x.decision,reviewedAt:new Date(x.reviewed_at).toISOString(),idempotencyKey:x.idempotency_key,...(x.reason?{reason:x.reason}:{})}}
