import { createHash } from "node:crypto";
import type { Pool } from "pg";
import type { NormalizedSourceItem, SourceDefinition, SourceExecutionMode } from "../../sources/src/index.ts";

export interface StoredSourceItem { readonly id: string; readonly sourceId: string; readonly externalId?: string | undefined; readonly canonicalUrl: string; readonly contentHash: string; readonly normalizedTitle: string; }
export type DuplicateKind = "CANONICAL_URL" | "EXTERNAL_ID" | "CONTENT_HASH";

export class PostgresSourceRadarRepository {
  readonly pool: Pool;
  constructor(pool: Pool) { this.pool=pool; }
  async upsertSourceDefinition(source: SourceDefinition): Promise<void> { await this.pool.query(`INSERT INTO source_definitions (id,name,organization,feed_url,definition,enabled) VALUES ($1,$2,$3,$4,$5::jsonb,$6) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, organization=EXCLUDED.organization, feed_url=EXCLUDED.feed_url, definition=EXCLUDED.definition, enabled=EXCLUDED.enabled, updated_at=CURRENT_TIMESTAMP`, [source.id, source.name, source.organization, source.feedUrl, JSON.stringify(source), source.enabled]); }
  async startRun(id: string, sourceId: string, mode: SourceExecutionMode, startedAt: string): Promise<void> { await this.pool.query(`INSERT INTO source_fetch_runs (id,source_id,mode,status,started_at) VALUES ($1,$2,$3,'RUNNING',$4)`, [id,sourceId,mode,startedAt]); }
  async finishRun(id: string, status: "SUCCEEDED" | "FAILED" | "SKIPPED", finishedAt: string, counts: {found:number; fresh:number; duplicate:number}, error?: {code:string; message:string}): Promise<void> { await this.pool.query(`UPDATE source_fetch_runs SET status=$2,finished_at=$3,items_found=$4,items_new=$5,items_duplicate=$6,error_code=$7,error_message=$8 WHERE id=$1`, [id,status,finishedAt,counts.found,counts.fresh,counts.duplicate,error?.code ?? null,error?.message ?? null]); }
  async findExact(item: NormalizedSourceItem): Promise<{item:StoredSourceItem; kind:DuplicateKind} | undefined> { const tests: readonly [DuplicateKind,string, string][] = [["CANONICAL_URL","canonical_url",item.canonicalUrl],["EXTERNAL_ID","external_id",item.externalId ?? ""],["CONTENT_HASH","content_hash",item.contentHash]]; for (const [kind,column,value] of tests) { if (!value) continue; const result=await this.pool.query(`SELECT id,source_id,external_id,canonical_url,content_hash,title FROM collected_source_items WHERE source_id=$1 AND ${column}=$2 LIMIT 1`,[item.sourceId,value]); const row=result.rows[0]; if(row) return {kind,item:{id:row.id,sourceId:row.source_id,externalId:row.external_id ?? undefined,canonicalUrl:row.canonical_url,contentHash:row.content_hash,normalizedTitle:row.title}}; } return undefined; }
  async listBySource(sourceId: string): Promise<readonly StoredSourceItem[]> { const result=await this.pool.query(`SELECT id,source_id,external_id,canonical_url,content_hash,title FROM collected_source_items WHERE source_id=$1 ORDER BY created_at DESC LIMIT 100`,[sourceId]); return result.rows.map((row)=>({id:row.id,sourceId:row.source_id,externalId:row.external_id ?? undefined,canonicalUrl:row.canonical_url,contentHash:row.content_hash,normalizedTitle:row.title})); }
  async saveItem(item: NormalizedSourceItem, collectedAt: string, editorialNewsId: string, similarityScore: number): Promise<StoredSourceItem> { const id=`source-item-${shortHash(item.sourceId+item.contentHash)}`; await this.pool.query(`INSERT INTO collected_source_items (id,source_id,external_id,canonical_url,title,summary,published_at,updated_at_source,collected_at,content_hash,editorial_news_id,similarity_score) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT (source_id, canonical_url) DO NOTHING`,[id,item.sourceId,item.externalId ?? null,item.canonicalUrl,item.normalizedTitle,item.normalizedSummary ?? null,item.publishedAt ?? null,item.updatedAt ?? null,collectedAt,item.contentHash,editorialNewsId,similarityScore]); return {id,sourceId:item.sourceId,externalId:item.externalId,canonicalUrl:item.canonicalUrl,contentHash:item.contentHash,normalizedTitle:item.normalizedTitle}; }
  async recordDuplicate(item: NormalizedSourceItem, match: {item:StoredSourceItem;kind:DuplicateKind}, detectedAt: string): Promise<void> { await this.pool.query(`INSERT INTO source_item_duplicates (id,source_id,incoming_external_id,incoming_canonical_url,incoming_content_hash,canonical_item_id,match_type,detected_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING`,[`source-duplicate-${shortHash(item.contentHash+match.kind)}`,item.sourceId,item.externalId ?? null,item.canonicalUrl,item.contentHash,match.item.id,match.kind,detectedAt]); }
}
function shortHash(value:string):string{return createHash("sha256").update(value).digest("hex").slice(0,24);}
