import type {Pool,PoolClient,QueryResultRow} from "pg";
import type {EditorialDraft} from "../../content-engine/src/index.ts";
import type {PublicationContext,PublicationFile,PublicationPackage,PublicationPackageRepository} from "../../application/src/index.ts";
import {PublicationPackageError,publicationSlug} from "../../application/src/index.ts";
import {withTransaction} from "./client.ts";
export class PostgresPublicationPackageRepository implements PublicationPackageRepository {
 private readonly pool:Pool;constructor(pool:Pool){this.pool=pool}
 async listEligible(){const r=await this.pool.query<{id:string}>(`SELECT d.id FROM editorial_drafts d JOIN editorial_news n ON n.id=d.news_id WHERE n.state IN('APPROVED','READY_FOR_PUBLICATION') AND n.current_draft_version_id=d.id ORDER BY d.created_at`);return (await Promise.all(r.rows.map(x=>this.loadApproved(x.id)))).filter((x):x is PublicationContext=>x!==undefined)}
 async loadApproved(id:string){const x=(await this.pool.query<QueryResultRow>(`SELECT d.*,n.state,n.lock_version,rd.id decision_id,rd.reviewer_id,rd.reviewed_at,(SELECT jsonb_agg(jsonb_build_object('evidenceId',c.evidence_id,'claimId',c.claim_id,'sourceId',c.source_id,'canonicalUrl',c.canonical_url,'title',c.page_title,'publishedAt',c.published_at)) FROM editorial_draft_citations c WHERE c.draft_id=d.id) citations,v.warnings FROM editorial_drafts d JOIN editorial_news n ON n.id=d.news_id JOIN editorial_review_decisions rd ON rd.draft_id=d.id AND rd.decision='APPROVE' JOIN editorial_draft_validations v ON v.draft_id=d.id WHERE d.id=$1 ORDER BY rd.created_at DESC LIMIT 1`,[id])).rows[0];if(!x)return undefined;const draft={draftId:x.id,newsId:x.news_id,briefId:x.brief_id,format:x.format,language:x.language,title:x.title,body:x.body,sourceCitations:x.citations??[],warnings:x.warnings??[],prohibitedClaimsChecked:true,validationStatus:x.validation_status,generatorId:x.generator_id,generatorVersion:x.generator_version,createdAt:new Date(x.created_at).toISOString(),...(x.subtitle?{subtitle:x.subtitle}:{})} as EditorialDraft;return {newsId:x.news_id,newsVersion:x.lock_version,newsState:x.state,draft,draftVersion:x.version_number,approvalDecisionId:x.decision_id,reviewerId:x.reviewer_id,approvedAt:new Date(x.reviewed_at).toISOString()}}
 save(input:{pkg:PublicationPackage;files:readonly PublicationFile[];idempotencyKey:string;commandId:string}){return withTransaction(this.pool,c=>save(c,input))}
 async findByIdempotency(key:string){const x=(await this.pool.query<QueryResultRow>(packageQuery+` WHERE p.idempotency_key=$1`,[key])).rows[0];return x?map(x):undefined}
 async get(id:string){const x=(await this.pool.query<QueryResultRow>(packageQuery+` WHERE p.id=$1`,[id])).rows[0];return x?map(x):undefined}
 async list(){const r=await this.pool.query<QueryResultRow>(packageQuery+` ORDER BY p.created_at,p.id`);return r.rows.map(map)}
}
async function save(c:PoolClient,input:{pkg:PublicationPackage;files:readonly PublicationFile[];idempotencyKey:string;commandId:string}){
 const prior=(await c.query<QueryResultRow>(`SELECT * FROM publication_packages WHERE idempotency_key=$1 FOR UPDATE`,[input.idempotencyKey])).rows[0];if(prior){if(prior.functional_fingerprint!==input.pkg.functionalFingerprint)throw new PublicationPackageError("PUBLICATION_PACKAGE_IDEMPOTENCY_CONFLICT","Idempotency conflict.");return {pkg:map(prior),replayed:true}}
 const x=(await c.query<QueryResultRow>(`SELECT n.state,n.lock_version,n.current_approval_request_id,d.version_number FROM editorial_news n JOIN editorial_drafts d ON d.id=n.current_draft_version_id WHERE n.id=$1 AND d.id=$2 FOR UPDATE OF n,d`,[input.pkg.newsId,input.pkg.draftId])).rows[0];if(!x||(x.state!=="APPROVED"&&x.state!=="READY_FOR_PUBLICATION"))throw new PublicationPackageError("PUBLICATION_PACKAGE_NOT_APPROVED","News is not approved.");if(x.lock_version!==input.pkg.newsVersion||x.version_number!==input.pkg.draftVersion)throw new PublicationPackageError("PUBLICATION_PACKAGE_VERSION_MISMATCH","Approved version changed.");
 await c.query(`INSERT INTO publication_packages(id,news_id,news_version,draft_id,draft_version,approval_decision_id,destination,policy_id,policy_version,content_hash,functional_fingerprint,status,reviewer_id,approved_at,created_at,exported_at,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'READY_FOR_PUBLICATION',$12,$13,$14,$14,$15)`,[input.pkg.publicationId,input.pkg.newsId,input.pkg.newsVersion,input.pkg.draftId,input.pkg.draftVersion,input.pkg.approvalDecisionId,input.pkg.destination,input.pkg.policyId,input.pkg.policyVersion,input.pkg.contentHash,input.pkg.functionalFingerprint,input.pkg.reviewerId,input.pkg.approvedAt,input.pkg.createdAt,input.idempotencyKey]);
 for(const f of input.files)await c.query(`INSERT INTO publication_package_files(publication_id,file_role,relative_path,content_hash,size_bytes,created_at) VALUES($1,$2,$3,$4,$5,$6)`,[input.pkg.publicationId,f.role,f.relativePath,f.contentHash,f.sizeBytes,input.pkg.createdAt]);
 for(const citation of input.pkg.citations)await c.query(`INSERT INTO publication_package_citations(publication_id,citation_id,source,title,canonical_url,claim_id,evidence_id,published_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[input.pkg.publicationId,`${citation.evidenceId}:${citation.claimId}`,citation.sourceId,citation.title,citation.canonicalUrl,citation.claimId,citation.evidenceId,citation.publishedAt??null]);
 await c.query(`INSERT INTO approval_actions(id,news_id,approval_request_id,draft_version_id,decision,actor_type,actor_id,reason,idempotency_key,created_at) SELECT $1,$2,$3,$4,'APPROVE','HUMAN',$5,'publication compatibility',$6,$7 WHERE NOT EXISTS(SELECT 1 FROM approval_actions WHERE approval_request_id=$3 AND decision='APPROVE')`,[`${input.pkg.approvalDecisionId}:legacy`,input.pkg.newsId,x.current_approval_request_id,input.pkg.draftId,input.pkg.reviewerId,`${input.idempotencyKey}:legacy`,input.pkg.approvedAt]);
 await c.query(`UPDATE editorial_news SET state='READY_FOR_PUBLICATION',lock_version=lock_version+1,updated_at=$1 WHERE id=$2`,[input.pkg.createdAt,input.pkg.newsId]);
 await c.query(`INSERT INTO audit_events(id,news_id,previous_state,new_state,action,actor_type,actor_id,content_version_id,idempotency_key,technical_payload,occurred_at) VALUES($1,$2,$3,'READY_FOR_PUBLICATION','PUBLICATION_PACKAGE_READY','HUMAN',$4,$5,$6,$7::jsonb,$8)`,[`${input.commandId}:ready`,input.pkg.newsId,x.state,input.pkg.reviewerId,input.pkg.draftId,input.idempotencyKey,JSON.stringify({publicationId:input.pkg.publicationId,destination:input.pkg.destination,contentHash:input.pkg.contentHash,policy:input.pkg.policyVersion}),input.pkg.createdAt]);
 return {pkg:input.pkg,replayed:false}
}
const packageQuery=`SELECT p.*,d.format draft_format,d.title,d.subtitle,d.body,v.warnings,
 COALESCE((SELECT jsonb_agg(jsonb_build_object('evidenceId',c.evidence_id,'claimId',c.claim_id,'sourceId',c.source,'canonicalUrl',c.canonical_url,'title',c.title,'publishedAt',c.published_at)) FROM publication_package_citations c WHERE c.publication_id=p.id),'[]') citations
 FROM publication_packages p JOIN editorial_drafts d ON d.id=p.draft_id JOIN editorial_draft_validations v ON v.draft_id=d.id`;
function map(x:QueryResultRow):PublicationPackage{return {publicationId:x.id,newsId:x.news_id,newsVersion:x.news_version,draftId:x.draft_id,draftVersion:x.draft_version,draftFormat:x.draft_format??"UNKNOWN",approvalDecisionId:x.approval_decision_id,reviewerId:x.reviewer_id,approvedAt:new Date(x.approved_at).toISOString(),destination:x.destination,policyId:x.policy_id,policyVersion:x.policy_version,title:x.title??"",...(x.subtitle?{subtitle:x.subtitle}:{}),body:x.body??"",...(x.destination==="WEBSITE_EXPORT"?{slug:publicationSlug(String(x.title??""),String(x.id))}:{}),citations:x.citations??[],warnings:x.warnings??[],contentHash:x.content_hash,functionalFingerprint:x.functional_fingerprint,status:x.status,createdAt:new Date(x.created_at).toISOString()}}
