import type {Pool,PoolClient,QueryResultRow} from "pg";
import type {PublicationPackage,ReadyWebsitePackage,WebsitePublicationPlan,WebsitePublicationPlanRepository} from "../../application/src/index.ts";
import {publicationSlug,WebsitePublicationPlanningError} from "../../application/src/index.ts";
import {withTransaction} from "./client.ts";

export class PostgresWebsitePublicationPlanRepository implements WebsitePublicationPlanRepository {
 private readonly pool:Pool;constructor(pool:Pool){this.pool=pool}
 async listReadyPackages(){const r=await this.pool.query<{id:string}>(`SELECT id FROM publication_packages WHERE destination='WEBSITE_EXPORT' AND status='READY_FOR_PUBLICATION' ORDER BY created_at,id`);return (await Promise.all(r.rows.map(x=>this.loadReadyPackage(x.id)))).filter((x):x is ReadyWebsitePackage=>x!==undefined)}
 async loadReadyPackage(id:string){const row=(await this.pool.query<QueryResultRow>(packageQuery,[id])).rows[0];if(!row)return undefined;const files=(await this.pool.query<QueryResultRow>(`SELECT file_role,relative_path,content_hash,size_bytes FROM publication_package_files WHERE publication_id=$1 ORDER BY file_role`,[id])).rows.map(x=>({role:x.file_role,relativePath:x.relative_path,contentHash:x.content_hash,sizeBytes:x.size_bytes}));return {pkg:mapPackage(row),files} as ReadyWebsitePackage}
 async findByIdempotency(key:string){const row=(await this.pool.query<QueryResultRow>(planQuery+` WHERE p.idempotency_key=$1`,[key])).rows[0];return row?mapPlan(row):undefined}
 save(input:{plan:WebsitePublicationPlan;idempotencyKey:string;commandId:string}){return withTransaction(this.pool,c=>save(c,input))}
 async get(id:string){const row=(await this.pool.query<QueryResultRow>(planQuery+` WHERE p.id=$1`,[id])).rows[0];return row?mapPlan(row):undefined}
 async list(){const r=await this.pool.query<QueryResultRow>(planQuery+` ORDER BY p.created_at,p.id`);return r.rows.map(mapPlan)}
}
async function save(c:PoolClient,input:{plan:WebsitePublicationPlan;idempotencyKey:string;commandId:string}){
 const previous=(await c.query<QueryResultRow>(planQuery+` WHERE p.idempotency_key=$1 FOR UPDATE`,[input.idempotencyKey])).rows[0];
 if(previous){const plan=mapPlan(previous);if(plan.functionalFingerprint!==input.plan.functionalFingerprint)throw new WebsitePublicationPlanningError("WEBSITE_PUBLICATION_IDEMPOTENCY_CONFLICT","Idempotency key conflict.");return {plan,replayed:true}}
 const source=(await c.query<QueryResultRow>(`SELECT id,news_id,draft_id,draft_version,content_hash,status,destination FROM publication_packages WHERE id=$1 FOR UPDATE`,[input.plan.publicationId])).rows[0];
 if(!source||source.status!=="READY_FOR_PUBLICATION"||source.destination!=="WEBSITE_EXPORT")throw new WebsitePublicationPlanningError("WEBSITE_PUBLICATION_PACKAGE_NOT_READY","Ready website package not found.");
 if(source.content_hash!==input.plan.packageContentHash||source.news_id!==input.plan.newsId||source.draft_id!==input.plan.draftId||source.draft_version!==input.plan.draftVersion)throw new WebsitePublicationPlanningError("WEBSITE_PUBLICATION_PACKAGE_INVALID","Package identity changed.");
 try{
  await c.query(`INSERT INTO website_publication_plans(id,publication_id,news_id,draft_id,draft_version,mode,target_profile_id,profile_version,public_base_url,legacy_technical_base_url,policy_id,policy_version,slug,source_files,destination_files,package_content_hash,functional_fingerprint,status,validation_status,provisional_public_url,detected_platform,publication_strategy,content_directory,route_pattern,requires_build,requires_restart,warnings,idempotency_key,command_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,$15::jsonb,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27::jsonb,$28,$29,$30)`,[input.plan.planId,input.plan.publicationId,input.plan.newsId,input.plan.draftId,input.plan.draftVersion,input.plan.mode,input.plan.targetProfileId,input.plan.profileVersion,input.plan.publicBaseUrl,input.plan.legacyTechnicalBaseUrl??null,input.plan.policyId,input.plan.policyVersion,input.plan.slug,JSON.stringify(input.plan.sourceFiles),JSON.stringify(input.plan.destinationFiles),input.plan.packageContentHash,input.plan.functionalFingerprint,input.plan.status,input.plan.validationStatus,input.plan.provisionalPublicUrl,input.plan.detectedPlatform,input.plan.publicationStrategy,input.plan.contentDirectory,input.plan.routePattern,tri(input.plan.requiresBuild),tri(input.plan.requiresRestart),JSON.stringify(input.plan.warnings),input.idempotencyKey,input.commandId,input.plan.createdAt]);
  for(const op of input.plan.operations)await c.query(`INSERT INTO website_publication_plan_operations(plan_id,position,operation_code,description,source_path,destination_path,condition,required,local_execution,status,is_remote) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[input.plan.planId,op.position,op.code,op.description,op.sourcePath??null,op.destinationPath??null,op.condition,op.required,op.localExecution,op.status,op.remote]);
  for(const prerequisite of input.plan.prerequisites)await c.query(`INSERT INTO website_publication_plan_prerequisites(plan_id,prerequisite_code,description,required,status) VALUES($1,$2,$3,$4,$5)`,[input.plan.planId,prerequisite.code,prerequisite.description,prerequisite.required,prerequisite.status]);
  for(const [suffix,action] of [["created","WEBSITE_PUBLICATION_PLAN_CREATED"],["validated","WEBSITE_PUBLICATION_PLAN_VALIDATED"],["completed","WEBSITE_PUBLICATION_DRY_RUN_COMPLETED"]] as const)await c.query(`INSERT INTO audit_events(id,news_id,previous_state,new_state,action,actor_type,actor_id,idempotency_key,technical_payload,occurred_at) SELECT $1,$2,n.state,n.state,$3,'SYSTEM','website-publication-planner',$4,$5::jsonb,$6 FROM editorial_news n WHERE n.id=$2`,[`${input.commandId}:${suffix}`,input.plan.newsId,action,`${input.idempotencyKey}:${suffix}`,JSON.stringify({planId:input.plan.planId,publicationId:input.plan.publicationId,mode:"DRY_RUN",policyVersion:input.plan.policyVersion}),input.plan.createdAt]);
 }catch(error){if((error as {code?:string}).code==="23505")throw new WebsitePublicationPlanningError("WEBSITE_PUBLICATION_PLAN_CONFLICT","A different plan already exists for this publication and policy.");throw error}
 return {plan:input.plan,replayed:false};
}
const packageQuery=`SELECT p.*,d.format draft_format,d.title,d.subtitle,d.body,v.warnings,COALESCE((SELECT jsonb_agg(jsonb_build_object('evidenceId',c.evidence_id,'claimId',c.claim_id,'sourceId',c.source,'canonicalUrl',c.canonical_url,'title',c.title,'publishedAt',c.published_at)) FROM publication_package_citations c WHERE c.publication_id=p.id),'[]') citations FROM publication_packages p JOIN editorial_drafts d ON d.id=p.draft_id JOIN editorial_draft_validations v ON v.draft_id=d.id WHERE p.id=$1 AND p.destination='WEBSITE_EXPORT' AND p.status='READY_FOR_PUBLICATION'`;
function mapPackage(x:QueryResultRow):PublicationPackage{return {publicationId:x.id,newsId:x.news_id,newsVersion:x.news_version,draftId:x.draft_id,draftVersion:x.draft_version,draftFormat:x.draft_format,approvalDecisionId:x.approval_decision_id,reviewerId:x.reviewer_id,approvedAt:new Date(x.approved_at).toISOString(),destination:x.destination,policyId:x.policy_id,policyVersion:x.policy_version,title:x.title,...(x.subtitle?{subtitle:x.subtitle}:{}),body:x.body,slug:publicationSlug(x.title,x.id),citations:x.citations??[],warnings:x.warnings??[],contentHash:x.content_hash,functionalFingerprint:x.functional_fingerprint,status:x.status,createdAt:new Date(x.created_at).toISOString()}}
const planQuery=`SELECT p.*,COALESCE((SELECT jsonb_agg(jsonb_strip_nulls(jsonb_build_object('position',o.position,'code',o.operation_code,'description',o.description,'sourcePath',o.source_path,'destinationPath',o.destination_path,'condition',o.condition,'required',o.required,'localExecution',o.local_execution,'status',o.status,'remote',o.is_remote)) ORDER BY o.position) FROM website_publication_plan_operations o WHERE o.plan_id=p.id),'[]') operations,COALESCE((SELECT jsonb_agg(jsonb_build_object('code',r.prerequisite_code,'description',r.description,'required',r.required,'status',r.status) ORDER BY r.prerequisite_code) FROM website_publication_plan_prerequisites r WHERE r.plan_id=p.id),'[]') prerequisites FROM website_publication_plans p`;
function mapPlan(x:QueryResultRow):WebsitePublicationPlan{return {planId:x.id,publicationId:x.publication_id,newsId:x.news_id,draftId:x.draft_id,draftVersion:x.draft_version,mode:x.mode,targetProfileId:x.target_profile_id,profileVersion:x.profile_version,publicBaseUrl:x.public_base_url,...(x.legacy_technical_base_url?{legacyTechnicalBaseUrl:x.legacy_technical_base_url}:{}),policyId:x.policy_id,policyVersion:x.policy_version,sourceFiles:x.source_files??[],destinationFiles:x.destination_files??[],slug:x.slug,packageContentHash:x.package_content_hash,functionalFingerprint:x.functional_fingerprint,status:x.status,validationStatus:x.validation_status,provisionalPublicUrl:x.provisional_public_url,detectedPlatform:x.detected_platform,publicationStrategy:x.publication_strategy,contentDirectory:x.content_directory,routePattern:x.route_pattern,requiresBuild:untri(x.requires_build),requiresRestart:untri(x.requires_restart),operations:x.operations??[],prerequisites:x.prerequisites??[],warnings:x.warnings??[],createdAt:new Date(x.created_at).toISOString()}}
function tri(value:boolean|"UNKNOWN"){return value==="UNKNOWN"?"UNKNOWN":value?"TRUE":"FALSE"}
function untri(value:string):boolean|"UNKNOWN"{return value==="UNKNOWN"?"UNKNOWN":value==="TRUE"}
