import {createHash} from "node:crypto";
import {mkdir,lstat,open,readFile,rename,unlink,writeFile} from "node:fs/promises";
import {dirname,join,relative,resolve} from "node:path";
import type {EditorialCitation,EditorialDraft,EditorialWarning} from "../../content-engine/src/index.ts";

export const PUBLICATION_PACKAGE_POLICY={id:"andre-studio-publication-package",version:"andre-studio-publication-package-v1"} as const;
export type PublicationDestination="LINKEDIN_EXPORT"|"WEBSITE_EXPORT";
export type PublicationPackageStatus="CREATED"|"VALIDATED"|"EXPORTED"|"READY_FOR_PUBLICATION"|"PUBLISHED"|"FAILED";
export interface PublicationPackage {publicationId:string;newsId:string;newsVersion:number;draftId:string;draftVersion:number;draftFormat:string;approvalDecisionId:string;reviewerId:string;approvedAt:string;destination:PublicationDestination;policyId:string;policyVersion:string;title:string;subtitle?:string;body:string;slug?:string;citations:readonly EditorialCitation[];warnings:readonly EditorialWarning[];contentHash:string;functionalFingerprint:string;status:PublicationPackageStatus;createdAt:string}
export interface PublicationContext {newsId:string;newsVersion:number;newsState:string;draft:EditorialDraft;draftVersion:number;approvalDecisionId:string;reviewerId:string;approvedAt:string}
export interface PublicationFile {role:"CONTENT_MARKDOWN"|"CONTENT_JSON"|"MANIFEST";relativePath:string;content:string;contentHash:string;sizeBytes:number}
export interface PublicationExportResult {files:readonly PublicationFile[];replayed:boolean}
export interface PublicationPackageRepository {listEligible():Promise<PublicationContext[]>;loadApproved(draftId:string):Promise<PublicationContext|undefined>;findByIdempotency(key:string):Promise<PublicationPackage|undefined>;save(input:{pkg:PublicationPackage;files:readonly PublicationFile[];idempotencyKey:string;commandId:string}):Promise<{pkg:PublicationPackage;replayed:boolean}>;get(id:string):Promise<PublicationPackage|undefined>;list():Promise<PublicationPackage[]>}
export interface PublicationExporter {export(pkg:PublicationPackage):Promise<PublicationExportResult>;cleanup(files:readonly PublicationFile[]):Promise<void>}
export class PublicationPackageError extends Error {readonly code:string;constructor(code:string,message:string){super(message);this.name="PublicationPackageError";this.code=code}}
const stable=(v:unknown)=>JSON.stringify(v,Object.keys(v as object).sort()),sha=(v:string)=>createHash("sha256").update(v).digest("hex");
export function publicationSlug(title:string,id:string){const base=title.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80).replace(/-$/,"");return base||`publication-${id.slice(-10)}`}
export function buildPublicationPackage(context:PublicationContext,destination:PublicationDestination,createdAt:string):PublicationPackage {
 if(context.newsState!=="APPROVED"&&context.newsState!=="READY_FOR_PUBLICATION")throw new PublicationPackageError("PUBLICATION_PACKAGE_NOT_APPROVED","Only human-approved news is eligible.");
 if(!context.reviewerId||!context.approvalDecisionId)throw new PublicationPackageError("PUBLICATION_PACKAGE_APPROVAL_NOT_FOUND","Human approval is required.");
 if(context.draft.validationStatus==="BLOCKED")throw new PublicationPackageError("PUBLICATION_PACKAGE_VALIDATION_BLOCKED","Blocked draft.");
 if(context.draft.sourceCitations.length===0)throw new PublicationPackageError("PUBLICATION_PACKAGE_CITATION_MISSING","Citations required.");
 if(destination!=="LINKEDIN_EXPORT"&&destination!=="WEBSITE_EXPORT")throw new PublicationPackageError("PUBLICATION_PACKAGE_DESTINATION_NOT_SUPPORTED","Unsupported destination.");
 const contentHash=sha(stable({title:context.draft.title,subtitle:context.draft.subtitle??null,body:context.draft.body,citations:context.draft.sourceCitations,warnings:context.draft.warnings,destination,policy:PUBLICATION_PACKAGE_POLICY.version}));
 const functionalFingerprint=sha(stable({newsId:context.newsId,newsVersion:context.newsVersion,draftId:context.draft.draftId,draftVersion:context.draftVersion,approvalDecisionId:context.approvalDecisionId,destination,policy:PUBLICATION_PACKAGE_POLICY,contentHash}));
 const publicationId=`publication-${functionalFingerprint.slice(0,24)}`,slug=destination==="WEBSITE_EXPORT"?publicationSlug(context.draft.title,publicationId):undefined;
 return {publicationId,newsId:context.newsId,newsVersion:context.newsVersion,draftId:context.draft.draftId,draftVersion:context.draftVersion,draftFormat:context.draft.format,approvalDecisionId:context.approvalDecisionId,reviewerId:context.reviewerId,approvedAt:context.approvedAt,destination,policyId:PUBLICATION_PACKAGE_POLICY.id,policyVersion:PUBLICATION_PACKAGE_POLICY.version,title:context.draft.title,...(context.draft.subtitle?{subtitle:context.draft.subtitle}:{}),body:context.draft.body,...(slug?{slug}:{}),citations:context.draft.sourceCitations,warnings:context.draft.warnings,contentHash,functionalFingerprint,status:"VALIDATED",createdAt};
}
export function validatePublicationPackage(pkg:PublicationPackage):"VALID"|"VALID_WITH_WARNINGS"|"BLOCKED" {if(!pkg.title||pkg.title.length>200||!pkg.body||pkg.body.length>(pkg.destination==="LINKEDIN_EXPORT"?5000:50000)||pkg.citations.length<1||pkg.citations.length>20||pkg.warnings.length>20||/<[^>]+>|(?:javascript|data|file):/i.test(`${pkg.title}\n${pkg.body}`))return "BLOCKED";if(pkg.citations.some(c=>!/^https:\/\//.test(c.canonicalUrl)))return "BLOCKED";return pkg.warnings.length?"VALID_WITH_WARNINGS":"VALID"}
function yaml(v:string){return JSON.stringify(v.replace(/[\r\n]+/g," "))}
function rendered(pkg:PublicationPackage):{md:string;json:string;contentPath:string}{
 const sources=pkg.citations.map(c=>`- ${c.title}: ${c.canonicalUrl}`).join("\n"),base=pkg.destination==="LINKEDIN_EXPORT"?`linkedin/${pkg.publicationId}`:`website/${pkg.slug}`;
 const header=pkg.destination==="LINKEDIN_EXPORT"?`---\ndestination: linkedin\nstatus: ready_for_publication\npublicationId: ${yaml(pkg.publicationId)}\ndraftId: ${yaml(pkg.draftId)}\ndraftVersion: ${pkg.draftVersion}\napprovedBy: ${yaml(pkg.reviewerId)}\n---\n\n${pkg.body}\n\nFontes para conferência:\n${sources}\n\n> Arquivo local; conteúdo ainda não publicado.\n`:`---\ntitle: ${yaml(pkg.title)}\nsubtitle: ${yaml(pkg.subtitle??"")}\nslug: ${yaml(pkg.slug??"")}\nauthor: \"André Rodrigues\"\nbrand: \"AndréStudio.dev\"\nstatus: \"ready_for_publication\"\ndraftId: ${yaml(pkg.draftId)}\ndraftVersion: ${pkg.draftVersion}\npublicationId: ${yaml(pkg.publicationId)}\napprovedBy: ${yaml(pkg.reviewerId)}\napprovedAt: ${yaml(pkg.approvedAt)}\nsources:\n${pkg.citations.map(c=>`  - ${yaml(c.canonicalUrl)}`).join("\n")}\n---\n\n# ${pkg.title}\n\n${pkg.subtitle?`${pkg.subtitle}\n\n`:""}${pkg.body}\n\n## Fontes\n${sources}\n`;
 return {md:header,json:JSON.stringify({...pkg,status:"READY_FOR_PUBLICATION"},null,2)+"\n",contentPath:base};
}
export class LocalPublicationExporter implements PublicationExporter {
 private readonly root:string;constructor(root:string){if(!root||root.includes("..")||resolve(root)===resolve("."))throw new PublicationPackageError("PUBLICATION_PACKAGE_OUTPUT_PATH_INVALID","Output root invalid.");this.root=resolve(root)}
 async export(pkg:PublicationPackage){if(validatePublicationPackage(pkg)==="BLOCKED")throw new PublicationPackageError("PUBLICATION_PACKAGE_VALIDATION_BLOCKED","Package blocked.");const r=rendered(pkg),manifestPath=`manifests/${pkg.publicationId}.json`,contents=[["CONTENT_MARKDOWN",`${r.contentPath}.md`,r.md],["CONTENT_JSON",`${r.contentPath}.json`,r.json]] as const;const provisional=contents.map(([role,path,content])=>({role,relativePath:path,content,contentHash:sha(content),sizeBytes:Buffer.byteLength(content)}));const manifest=JSON.stringify({publicationId:pkg.publicationId,destination:pkg.destination,newsId:pkg.newsId,newsVersion:pkg.newsVersion,draftId:pkg.draftId,draftVersion:pkg.draftVersion,approvalDecisionId:pkg.approvalDecisionId,reviewerId:pkg.reviewerId,approvedAt:pkg.approvedAt,policyId:pkg.policyId,policyVersion:pkg.policyVersion,contentHash:pkg.contentHash,functionalFingerprint:pkg.functionalFingerprint,files:provisional.map(({content,...x})=>x),citations:pkg.citations,warnings:pkg.warnings,status:"READY_FOR_PUBLICATION",createdAt:pkg.createdAt},null,2)+"\n";const files:PublicationFile[]=[...provisional,{role:"MANIFEST",relativePath:manifestPath,content:manifest,contentHash:sha(manifest),sizeBytes:Buffer.byteLength(manifest)}];let replay=true;const created:string[]=[];try{for(const f of files){const target=this.safe(f.relativePath);await mkdir(dirname(target),{recursive:true});if((await lstat(dirname(target))).isSymbolicLink())throw new PublicationPackageError("PUBLICATION_PACKAGE_OUTPUT_PATH_INVALID","Symlink output directory is forbidden.");try{const existing=await readFile(target,"utf8");if(sha(existing)!==f.contentHash)throw new PublicationPackageError("PUBLICATION_PACKAGE_IDEMPOTENCY_CONFLICT","Existing output differs.");}catch(e){if((e as NodeJS.ErrnoException).code!=="ENOENT")throw e;replay=false;const temp=`${target}.tmp-${pkg.publicationId}`;try{await writeFile(temp,f.content,{flag:"wx"});const handle=await open(temp,"r");await handle.sync();await handle.close();await rename(temp,target);created.push(target)}catch(error){await unlink(temp).catch(()=>undefined);if((error as NodeJS.ErrnoException).code==="EEXIST")throw new PublicationPackageError("PUBLICATION_PACKAGE_IDEMPOTENCY_CONFLICT","Concurrent output exists.");throw error}}}return {files,replayed:replay}}catch(error){for(const path of created)await unlink(path).catch(()=>undefined);throw error}}
 async cleanup(files:readonly PublicationFile[]){for(const f of files)await unlink(this.safe(f.relativePath)).catch(()=>undefined)}
 private safe(path:string){if(path.startsWith("/")||path.includes("..")||path.includes("\\")||path.startsWith(".git/")||path.startsWith("node_modules/")||path.startsWith("packages/")||path.startsWith("apps/"))throw new PublicationPackageError("PUBLICATION_PACKAGE_OUTPUT_PATH_INVALID","Unsafe relative path.");const target=resolve(this.root,path);if(relative(this.root,target).startsWith(".."))throw new PublicationPackageError("PUBLICATION_PACKAGE_OUTPUT_PATH_INVALID","Path escapes output root.");return target}
}
export class PublicationPackageService {
 private readonly repo:PublicationPackageRepository;private readonly exporter:PublicationExporter;constructor(repo:PublicationPackageRepository,exporter:PublicationExporter){this.repo=repo;this.exporter=exporter}
 listEligibleDrafts(){return this.repo.listEligible()} getPublicationPackage(id:string){return this.repo.get(id)} listPublicationPackages(){return this.repo.list()}
 async getPublicationPreview(draftId:string,destination:PublicationDestination,createdAt:string){const c=await this.repo.loadApproved(draftId);if(!c)throw new PublicationPackageError("PUBLICATION_PACKAGE_DRAFT_NOT_FOUND","Approved draft not found.");return buildPublicationPackage(c,destination,createdAt)}
 async exportPackage(input:{draftId:string;destination:PublicationDestination;reviewerId:string;createdAt:string;idempotencyKey:string;commandId:string}){const prior=await this.repo.findByIdempotency(input.idempotencyKey);if(prior){if(prior.draftId!==input.draftId||prior.destination!==input.destination||prior.reviewerId!==input.reviewerId)throw new PublicationPackageError("PUBLICATION_PACKAGE_IDEMPOTENCY_CONFLICT","Idempotency conflict.");return {pkg:prior,files:[],replayed:true}}const pkg=await this.getPublicationPreview(input.draftId,input.destination,input.createdAt);if(pkg.reviewerId!==input.reviewerId)throw new PublicationPackageError("PUBLICATION_PACKAGE_APPROVAL_NOT_FOUND","Exporter must be the approving reviewer.");const exported=await this.exporter.export(pkg);try{const saved=await this.repo.save({pkg:{...pkg,status:"READY_FOR_PUBLICATION"},files:exported.files,idempotencyKey:input.idempotencyKey,commandId:input.commandId});return {...saved,files:exported.files,replayed:saved.replayed||exported.replayed}}catch(e){if(!exported.replayed)await this.exporter.cleanup(exported.files);throw e}}
}
